scilus/scilpy

scilpy/preprocessing/distortion_correction.py, scripts/scil_prepare_eddy_command.py, scripts/scil_prepare_topup_command.py
Rename the dwell time option by readout.
=> BF: Rename dwell time option with readout

requirements.txt, scripts/scil_validate_bids.py
Script to validate BIDS format and used in TractoFlow.
=> NF: script validate bids

scilpy/io/image.py, scripts/scil_apply_transform_to_image.py, scripts/scil_apply_transform_to_tractogram.py, scripts/scil_apply_warp_to_tractogram.py
Adress JC's comments post-PR about the transform scripts
=> Minor correction for transform scripts

.pep8speaks.yml
Add pep8 yml file for pep8speaks application.
=> NF: Add pep8speaks yml

scripts/scil_reorder_dwi_philips.py
This script has already been reviewed by @jchoude last month. Already ready for merging.
=> reorderDWIPhilips script

README.md, requirements-git.txt, requirements.txt, scilpy/io/utils.py, scripts/scil_convert_tractogram.py
- Now support everything handle by dipy (StatefulTractogram)
- reference argument for script is now added by a function
=> Transfert of the tractogram conversion script

scilpy/utils/streamlines.py, scripts/scil_streamlines_math.py
Transfert from bitbucket
Tested with Python3
=> Futurize streamlines math

scilpy/io/utils.py, scilpy/segment/streamlines.py, scripts/scil_filter_tractogram.py
Transfert of the scil_robust_tractogram_filtering_sequential.py script
- Support metadata
- Support TRK, TCK, VTK, etc. using StatefulTractogram
- Remove the notFiltered option (will use streamlines_math in the future)
=> Transfer filter tractogram

scilpy/utils/flip_tools.py, scilpy/utils/util.py, scripts/scil_add_tracking_mask_to_pft_maps.py, scripts/scil_convert_sh_basis.py, scripts/scil_flip_gradients.py
Add scil_add_tracking_mask_to_pft_maps.py, scil_convert_sh_basis.py, scil_flip_gradients.py
=> NF: Add new scripts in scilpy public

scilpy/tractanalysis/todi.py, scilpy/tractanalysis/todi_util.py, scripts/scil_compute_todi.py, scripts/scil_generate_priors_from_bundle.py
Transfert of the TODI and priors scripts, using the new StatefulTractogram.
Data for testing
https://drive.google.com/open?id=1I4iiUwXlcfx-traK9i5QpYU189DUG0Me
=> Futurize priors

scripts/scil_validate_bids.py
Add options and modify the possibilities for the readout time validation.
=> ENH: fix readout time on validate BIDS

scilpy/image/utils.py, scripts/scil_count_non_zero_voxels.py
Just need one review/approval for this PR
=> NF count_non_zero_voxels

requirements.txt, scilpy/io/utils.py, scilpy/segment/recobundlesx.py, scilpy/segment/voting_scheme.py, scripts/scil_recognize_multi_bundles.py, scripts/scil_recognize_single_bundle.py
Transfert of the single-atlas single-parameters Recobundles from scilpy as well as multi-atlas multi-parameters Recobundles from my personal repository (and all updated and tested in Python3)
One PR for both makes it easier to test, compare and since the algorithms and parameters are very similar in both it makes the review easier and faster.
Here is something to test it with, and a bash script to help.
https://drive.google.com/file/d/16Nr-udxbAhyLCE5x6qO5V8B-OGt37n2C/view?usp=sharing
=> Recobundlex standalone

requirements.txt, scripts/scil_visualize_bundlesList_mosaic.py, scripts/scil_visualize_bundles_mosaic.py
Plot in a table 6 views ( axial superior, axial inferior,  coronal posterior, coronal anterior, sagittal left, sagittal right) of N tractograms.
=> Plot N tractograms in a table 

scilpy/utils/image.py, scilpy/viz/screenshot.py, scripts/scil_screenshot_dti.py
For the QA of TractoInferno of P.Poulin this script was required to verify and uniformize the bvec of multiple database.
Same behaviour as before, simply converted to Python3
Now the template is any MNI152 nifti file (t1, t2, flair) in 1mm or 2mm isotropic (2mm recommanded for speed)
=> Futurize dti screenshot

scripts/scil_filter_streamlines_by_length.py
=> Change default maxL filter_streamlines_by_length

scripts/scil_validate_bids.py
Add a readout error and change IntendedFor type check
=> ENH add readout error

README.md, requirements.txt, scilpy/tractanalysis/robust_streamlines_metrics.pyx, scilpy/tractanalysis/streamlines_metrics.pyx, scilpy/tractanalysis/todi.py, scripts/scil_compress_streamlines.py, scripts/scil_perform_majority_vote.py, setup.py
Transfert of the scripts, added the cythonize portion from #7 (thx @jchoude).
=> Futurize majority vote

scilpy/io/image.py, scripts/scil_merge_sh.py
New script to merge sh from 2 different shells.
=> NF New script to merge sh

scilpy/tractanalysis/todi.py, scilpy/tractanalysis/todi_util.py, scripts/scil_compute_todi.py
Added comments and details to TODI functions.
=> Todi details

scilpy/io/utils.py, scripts/scil_assign_color_to_trk.py, scripts/scil_compute_todi.py, scripts/scil_convert_tractogram.py, scripts/scil_filter_tractogram.py, scripts/scil_perform_majority_vote.py, scripts/scil_recognize_single_bundle.py, scripts/scil_remove_invalid_streamlines.py, scripts/scil_streamlines_math.py
Add `_arg` to the function name for consistency
=> Renanme the function (adding arg)

scilpy/tracking/tools.py, scripts/scil_compute_streamlines_length_stats.py, scripts/scil_filter_streamlines_by_length.py
First of many PRs for tractometry.
=> Futurize tractometry 1

scripts/scil_filter_tractogram.py, scripts/scil_perform_majority_vote.py, scripts/scil_recognize_single_bundle.py, scripts/scil_streamlines_math.py
@arnaudbore did not know how to do a `git blame`
=> Removed forgotten post-merge warning

scilpy/io/utils.py, scripts/scil_compute_streamlines_length_stats.py, scripts/scil_count_streamlines.py, scripts/scil_filter_streamlines_by_length.py, scripts/scil_filter_tractogram.py
=> print json tract count before/after filtering

scripts/scil_count_streamlines.py
=> fix indent for scil_count_streamlines

scilpy/image/reslice.py, scripts/scil_resample_volume.py
Major bug fix about the resample. Add offset to the function to avoid the squarred pattern.
Here a data for testing: https://usherbrooke-my.sharepoint.com/:u:/g/personal/theg3301_usherbrooke_ca/ET1Na0V4kf5DtmBg_MNr4YIBPMlpm-F_EoGqUF7uStP8Zw?e=N3NvWO
=> BF: Fix resample issue

scilpy/samplingscheme/gen_scheme.py, scilpy/samplingscheme/multiple_shell_energy.py, scilpy/samplingscheme/optimize_scheme.py, scilpy/samplingscheme/save_scheme.py, scilpy/utils/bvec_bval_tools.py, scilpy/viz/sampling_scheme.py, scripts/scil_convert_gradients_fsl_to_mrtrix.py, scripts/scil_convert_gradients_mrtrix_to_fsl.py, scripts/scil_generate_sampling_scheme.py, scripts/scil_visualize_multi_shell.py
clean branch futurize gradients and viz shells see closed PR32
=> Futurize - gradients and shell vizualisation

requirements.txt
Change nibabel version to 3.0.1
=> Change nibabel version

scilpy/io/streamlines.py, scripts/scil_compute_connectivity.py
Not tested!! I don't know how to test rapidly.
=> Removing load_trk_in_voxel_space and usage

scilpy/utils/image.py, scripts/scil_combine_labels.py, scripts/scil_dilate_labels.py, scripts/scil_remove_labels.py, scripts/scil_reshape_to_reference.py
Utilitary scripts for Labels volume (e.g. wmparc)
1) to reshape the mgz to the t1 (using the transform in both files),
and use the ref shape dim and transform as output space.
2) dilate label, with some other options
3) combine labels from multiple different images
=> Wmparc utils

scripts/scil_flip_volume.py
Script to flip Nifti volume, Francois needed it
=> Flip volume

requirements.txt, scilpy/io/utils.py, scilpy/tractanalysis/reproducibility_measures.py, scripts/scil_perform_majority_vote.py, scripts/scil_summarize_bundles_binary_measures.py, scripts/scil_summarize_bundles_similarity_measures.py
Follow up from Tractostorm, this is related to PR #67 but for binary measures.
Here some testing data
https://drive.google.com/open?id=1AGnBd5fQIJYGB84LIw1rGDRxaWNqn5QV
=> binary summary script

scripts/scil_flip_streamlines.py
=> RF: added quick clarification

scripts/scil_compute_kurtosis_metrics.py
Addressing the remaining quick comments from PR #66
=> RF: quick DKI fixes

scripts/scil_compute_maps_for_particle_filter_tracking.py, scripts/scil_compute_pft.py, scripts/scil_extract_b0.py, scripts/scil_extract_dwi_shell.py, scripts/scil_mask_math.py, scripts/scil_streamlines_math.py
One important change: see scil_compute_pft.
fodf_sh_img = nib.load(args.sh_file) was called twice!
=> light changes Pep8

scripts/scil_validate_bids.py
Fix all possibilities of input folders.
=> Fix validate bids for TractoFlow

scilpy/samplingscheme/gen_scheme.py, scilpy/samplingscheme/multiple_shell_energy.py
=> Description didn't fit with our args

scripts/scil_endpoints_map.py
=> Fix endpoint map

scripts/scil_compute_maps_for_particle_filter_tracking.py, scripts/scil_resample_volume.py, scripts/scil_visualize_multi_shell.py, scripts/scil_visualize_seeds.py
Removing action=store and type=str in argparser for every scripts.
=> Removing default parameter in argparse

scilpy/samplingscheme/multiple_shell_energy.py, scilpy/samplingscheme/optimize_scheme.py, scilpy/samplingscheme/save_scheme.py
=> reorganize import in samplingscheme

scilpy/segment/models.py, scilpy/segment/recobundlesx.py, scilpy/segment/voting_scheme.py
=> reorganize import in segment

scripts/scil_clean_qbx_clusters.py, scripts/scil_compute_dti_metrics.py, scripts/scil_compute_fodf_max_in_ventricles.py, scripts/scil_dilate_labels.py, scripts/scil_extract_b0.py, scripts/scil_remove_outliers_ransac.py, scripts/scil_remove_similar_streamlines.py, scripts/scil_resample_volume.py, scripts/scil_run_nlmeans.py, scripts/scil_summarize_bundles_similarity_measures.py
From scily_cleanup_crew, Convert all "%s" % "text" to "{}".format("text") + Bash script tests running -h.
=> Replaced %s by {}.format()

.travis.yml, README.md, requirements.txt
Add travis to check the installation on python 3.5 3.6 3.7. Next PR on travis will be to test the --help options.
=> Nf add travis

scilpy/io/image.py, scilpy/io/utils.py, scilpy/utils/image.py, scripts/scil_compute_local_tracking.py, scripts/scil_compute_pft.py, scripts/scil_summarize_bundles_similarity_measures.py
Delete scilpy.io.utils.create_header_from_anat and replace by dipy.io.utils.create_tractogram_header in conjunction with dipy.io.utils.get_reference_info
=> Replaced create_header function

scilpy/io/utils.py
=> ENH: Remove unused imports

scilpy/image/operations.py
OrderedDict in the docstring, this will keep the order of operation as written. Much better for the description.
Added log operation (natural and base 10)
=> Update image/connectivity math (log, OrderedDict)

scripts/scil_compute_connectivity.py
A mistake was made a long time ago that autopep8 did not fix.
This is simply the results of running autopep8 on that file
=> fix_pep8_operator_space

scilpy/tractanalysis/tools.py, scilpy/tractanalysis/uncompress.pyx, scripts/scil_compute_connectivity.py, scripts/scil_decompose_connectivity.py
Fix error related to `get_fdata()` and `array_sequence.data`
Also fixed the issues/comments #190 #191 #189 
(Issue #191 is actually fixed in PR #188, but everything was tested with the same data)
=> Fix connectivity warning

scilpy/io/image.py, scripts/scil_compute_dti_metrics.py, scripts/scil_remove_labels.py
As discussed with @jchoude, @GuillaumeTh and @frheault here are two new functions to have a better control over the type of masks and labels inputs.
I will add a converted script with these new functions to have an example.
=> Add get_data for masks and label

scripts/scil_perform_majority_vote.py
Kurt pointed out an error in my code, I fixed it.
The script was not using the ratio_voxels correctly
=> Wrong use of ratio for volume in perform_majority_vote

scilpy/io/image.py, scripts/scil_filter_streamlines_by_length.py, scripts/scil_filter_tractogram.py
Data for testing: [here](https://drive.google.com/open?id=1FTDlAngdEuN1odEad61e9aZcKKhhkQwV)
=> improve json output when using filtering list

scilpy/io/image.py, scripts/scil_compute_dti_metrics.py
DTI metrics script crash when we give a mask. Setting the type as bool fixed the issue.
=> BF: Load mask as bool

scilpy/image/operations.py, scilpy/utils/image.py, scripts/scil_combine_labels.py, scripts/scil_connectivity_math.py, scripts/scil_dilate_labels.py, scripts/scil_image_math.py, scripts/scil_remove_invalid_streamlines.py, scripts/scil_split_volume_by_ids.py, scripts/scil_split_volume_by_labels.py
Update of labels and image_math scripts for `get_fdata()` and `get_data_as_label` for a project related to freesurfer, brainnetome, glasser atlas.
This prevents warnings from nibabel in the scripts I made for Max.
(We have to start fixing these warning somewhere, this is a first pass)
=> Brainnetome nibabel update

scilpy/preprocessing/distortion_correction.py, scripts/scil_prepare_eddy_command.py, scripts/scil_prepare_topup_command.py
A small improvement to support 4D reverse B0. We decided to mean the 4th dimension to speed up Topup.
A testing dataset:
https://usherbrooke-my.sharepoint.com/:u:/g/personal/theg3301_usherbrooke_ca/ERQ3ZbVpuM5Do8tHcrCrBl8BH9-2QrgV0ygPnwAARZhE_g?e=ekTfRc
This PR is for the next release of TractoFlow :beers:
=> Mean all rev_b0 of 4D

scripts/scil_recognize_multi_bundles.py, scripts/scil_recognize_single_bundle.py
Not sure these scripts had to be fixed (see #219) but I took the opportunity to uniformize the scripts.
Very small edits.
=> uniformize recognize_bundle scripts

requirements.txt, scilpy/image/resample_volume.py, scilpy/image/utils.py
Fix get_fdata() datatype to float32 to reduce memory and change requirements typo for dipy to be less strict
=> Fix datatype for fdata and change requirements

scilpy/utils/streamlines.py
=> Add key to dict

scripts/scil_run_commit.py
Adaption for new feature in COMMIT that allows the use of Singularity !
=> WIP - Local build commit

scilpy/io/fetcher.py, scripts/scil_visualize_bundles_mosaic.py, scripts/tests/test_compute_qbx.py, scripts/tests/test_compute_streamlines_density_map.py, scripts/tests/test_compute_streamlines_length_stats.py, scripts/tests/test_detect_streamlines_loops.py, scripts/tests/test_filter_streamlines_by_length.py, scripts/tests/test_filter_tractogram.py, scripts/tests/test_outlier_rejection.py, scripts/tests/test_perform_majority_vote.py, scripts/tests/test_verify_space_attributes_compatibility.py, scripts/tests/test_visualize_bundles_mosaic.py
Followup of testing, with scripts related to filtering.
=> Integration testing filtering

scilpy/io/fetcher.py, scripts/scil_compare_connectivity.py, scripts/scil_compute_connectivity.py, scripts/scil_compute_hdf5_average_density_map.py, scripts/tests/test_compare_connectivity.py, scripts/tests/test_compute_connectivity.py, scripts/tests/test_compute_hdf5_average_density_map.py, scripts/tests/test_decompose_connectivity.py, scripts/tests/test_evaluate_connectivity_measures.py, scripts/tests/test_filter_connectivity.py, scripts/tests/test_normalize_connectivity.py, scripts/tests/test_print_connectivity_filenames.py, scripts/tests/test_reorder_connectivity.py, scripts/tests/test_visualize_connectivity.py
Followup of testing, with scripts related to filtering.
=> Integration testing connectivity

scilpy/io/fetcher.py, scripts/scil_generate_priors_from_bundle.py, scripts/tests/test_apply_transform_to_image.py, scripts/tests/test_apply_transform_to_tractogram.py, scripts/tests/test_apply_warp_to_tractogram.py, scripts/tests/test_compute_todi.py, scripts/tests/test_generate_priors_from_bundle.py
Followup of testing, with scripts related to me and bst.
=> Integration testing bst 

scilpy/io/fetcher.py, scripts/scil_remove_similar_streamlines.py, scripts/tests/test_compute_streamlines_density_map.py, scripts/tests/test_convert_rgb.py, scripts/tests/test_count_non_zero_voxels.py, scripts/tests/test_count_streamlines.py, scripts/tests/test_crop_volume.py, scripts/tests/test_generate_gradient_sampling.py, scripts/tests/test_remove_similar_streamlines.py, scripts/tests/test_resample_volume.py, scripts/tests/test_reshape_to_reference.py, scripts/tests/test_run_nlmeans.py
Followup of testing, with utility scripts
=> Integration testing others

scilpy/io/fetcher.py, scripts/scil_compute_maps_for_particle_filter_tracking.py, scripts/tests/test_add_tracking_mask_to_pft_maps.py, scripts/tests/test_compute_local_tracking.py, scripts/tests/test_compute_maps_for_particle_filter_tracking.py, scripts/tests/test_compute_pft.py, scripts/tests/test_get_subset_streamlines.py, scripts/tests/test_image_math.py, scripts/tests/test_print_header.py, scripts/tests/test_shuffle_streamlines.py, scripts/tests/test_smooth_streamlines.py, scripts/tests/test_split_tractograms.py, scripts/tests/test_streamlines_math.py
Followup of testing, with scripts related to tracking and streamlines.
=> Integration testing tracking

scilpy/io/fetcher.py, scripts/tests/test_assign_color_to_trk.py, scripts/tests/test_bundle_mean_std.py, scripts/tests/test_bundle_mean_std_per_point.py, scripts/tests/test_bundle_volume.py, scripts/tests/test_bundle_volume_per_label.py, scripts/tests/test_bundle_voxel_label_map.py, scripts/tests/test_compute_bundle_profiles.py, scripts/tests/test_compute_centroid.py, scripts/tests/test_compute_metrics_stats_in_ROI.py, scripts/tests/test_compute_streamlines_density_map.py, scripts/tests/test_count_streamlines.py, scripts/tests/test_endpoints_map.py, scripts/tests/test_endpoints_metric.py, scripts/tests/test_label_and_distance_maps.py, scripts/tests/test_plot_mean_std_per_point.py, scripts/tests/test_resample_streamlines.py, scripts/tests/test_uniformize_streamlines_endpoints.py
Followup of testing, with scripts related to tractometry.
=> Integration testing tractometry

scilpy/io/fetcher.py, scripts/scil_compute_fodf_metrics.py, scripts/scil_screenshot_dti.py, scripts/tests/test_apply_bias_field_on_dwi.py, scripts/tests/test_compute_dti_metrics.py, scripts/tests/test_compute_fodf.py, scripts/tests/test_compute_fodf_max_in_ventricles.py, scripts/tests/test_compute_fodf_metrics.py, scripts/tests/test_compute_kurtosis_metrics.py, scripts/tests/test_compute_mean_fixel_afd_from_bundles.py, scripts/tests/test_compute_mean_frf.py, scripts/tests/test_compute_seed_density_map.py, scripts/tests/test_compute_sh_from_signal.py, scripts/tests/test_compute_ssst_frf.py, scripts/tests/test_convert_gradients_fsl_to_mrtrix.py, scripts/tests/test_convert_gradients_mrtrix_to_fsl.py, scripts/tests/test_convert_sh_basis.py, scripts/tests/test_crop_volume.py, scripts/tests/test_extract_b0.py, scripts/tests/test_extract_dwi_shell.py, scripts/tests/test_flip_gradients.py, scripts/tests/test_merge_sh.py, scripts/tests/test_remove_outliers_ransac.py, scripts/tests/test_screenshot_dti.py, scripts/tests/test_set_response_function.py
Following on testing, all scripts related to pre-processing and local model and derivatives.
=> Integration testing processing

scripts/scil_recognize_multi_bundles.py, scripts/scil_recognize_single_bundle.py
=> Forgotten matrix loading only txt in recognize

scilpy/image/resample_volume.py, scilpy/tractanalysis/grid_intersections.pyx, scilpy/utils/metrics_tools.py, scilpy/utils/streamlines.py, scripts/scil_bundle_mean_std_per_point.py, scripts/scil_compute_dti_metrics.py, scripts/scil_flip_volume.py, scripts/scil_label_and_distance_maps.py, scripts/scil_screenshot_dti.py
This and PR #272 were the main source of warning that were also the easiest to fix. That will be all I fix for now.
=> Fix get_affine and get_header warning

scilpy/io/fetcher.py, scripts/scil_reorder_connectivity.py, scripts/scil_visualize_connectivity.py, scripts/tests/test_reorder_connectivity.py
Modification for @mdesco first use. Refactor to have more intuitive use and input
Replaced multikey json with a simple two rows text file (x and y)
=> Reorder connectivity refactor

scripts/tests/test_compute_ihMT_maps.py
Split test in 3 tests and remove useless tmp_dir.
=> BF: Fix ihMT tests

scilpy/io/fetcher.py, scripts/scil_recognize_multi_bundles.py
=> Fix zenodo link for RBX

scripts/scil_save_connections_from_hdf5.py
Data to test is avalaible here:
[(https://drive.google.com/file/d/1cavj1VGavbPJCBbPdAN9dqz845Tza-tN/view?usp=sharing)]
=> Adding save_empty option to save connectivity

README.md
A simple line to direct people in the right direction for COMMIT
=> Update readme for lapack et blas

scilpy/image/operations.py, scilpy/io/fetcher.py, scripts/scil_image_math.py, scripts/tests/test_image_math.py
Concatenate 3D images into a single 4D image. Analogous to mrcat.
As suggested in #288
=> scil_image_math.py concat option

.travis.yml
Build automatically docker when push on master and build docker + singularity when tag is created.
Docker is upload on dockerhub and singularity upload on the release page of github.
=> Build docker and singularity

docs/requirements.txt, requirements.txt
=> Update pillow for security vulnerabilities

scilpy/io/fetcher.py, scripts/scil_reorder_connectivity.py, scripts/scil_visualize_connectivity.py, scripts/tests/test_reorder_connectivity.py
Final update for Maxime request of #282 
Cover more use case from connectoflow
=> Update for suffix and more robust visualisation

scilpy/segment/models.py, scripts/scil_remove_similar_streamlines.py, scripts/tests/test_remove_similar_streamlines.py
Useless and unstable, plus there was a mistake in the code
=> Refactor similar streamlines

containers/Dockerfile
=> Add jq and rename in the container

scripts/scil_compute_NODDI.py, scripts/scil_compute_freewater.py
scil_compute_NODDI.py
scil_compute_freewater.py
=> add compute only option

scripts/scil_normalize_connectivity.py
=> fix too fast merge of normalise_connectivity

scripts/scil_visualize_histogram.py, scripts/tests/__init__.py, scripts/tests/test_visualize_histogram.py
Script to visualize the histogram of metric values (FA and MD) from a binary mask.
Data to test the script: https://drive.google.com/file/d/158eKOLS0IBn1gKjRHBn-lQhWfbwwAPAF/view?usp=sharing
=> Add visualize histogram

requirements.txt, scilpy/viz/gradient_sampling.py, scilpy/viz/screenshot.py, scripts/scil_screenshot_bundle.py, scripts/scil_visualize_seeds.py
Self explanatory.
You can test that fury still works and displays streamlines by running `scil_visualize_bundle_mosaic.py` with the data here:
https://drive.google.com/drive/folders/1qgnXRayGJGPDOwuzqeC6clZWbOgc2b8x?usp=sharing
=> FIX: Update fury to 0.6.*

scripts/scil_generate_priors_from_bundle.py
Change datatype of mask to uint8,
faster saving due to endpoints compuation using (get data as mask in loop)
=> Infinite endpoints computation

scilpy/utils/bvec_bval_tools.py, scripts/scil_resample_bvals.py, scripts/tests/test_resample_bvals.py
Follow up of PR #367. Centroids are know sorted and the bvec file no longer required.
=> Resample bvals

Jenkinsfile
I keep travis file for now to transfert the docker part later
=> Update jenkins files

scilpy/io/fetcher.py, scripts/scil_execute_asymmetric_filtering.py, scripts/tests/test_execute_asymmetric_filtering.py, scripts/tests/test_visualize_fodf.py
Hi,
Add testing for full basis input to scripts
* `scil_visualize_fodf.py`
* `scil_execute_asymmetric_filtering.py`
Have a rockin' day!
=> TEST: Add tests for full basis input

scilpy/io/streamlines.py, scripts/scil_apply_transform_to_hdf5.py, scripts/scil_compute_connectivity.py
Must be merge before release
@arnaudbore @mdesco 
Just tested with connectoflow
=> Commit fix from Ale

scripts/scil_compute_todi.py, scripts/tests/test_compute_todi.py
Simplified TODI script, added details and default values in the help
for issue #408
=> Todi defaults

scripts/scil_concatenate_dwi.py, scripts/scil_extract_dwi_shell.py, scripts/tests/test_concatenate_dwi.py
New utility script.
This is a 'rarer', I didn't code any lazy saving (meaning if you fuse 100 DWI the final results is all in memory)
I also didn't code an approx. of bvals (meaning if you fuse 2 DWI with bval at 1001 and 999 they will be kept as is)
I also didn't check the data_type BUT there is a parameters that forces it.
=> Concatenate DWI

scripts/scil_compute_msmt_frf.py, scripts/scil_compute_ssst_frf.py
=> Default radius compute frf 

scripts/scil_compute_hdf5_average_density_map.py
Switch to with statement in for loops. Prevent corruption of file in the event of a nextflow crash
=> BF - more robust compute average hdf5 maps

scripts/scil_evaluate_connectivity_pairwise_agreement_measures.py
I added ssd and correlation coefficient calculations to scil_evaluate_connectivity_pairwise_agreement_measures.py
=> SSD and Correlation Coefficient

scilpy/tractanalysis/reproducibility_measures.py, scilpy/utils/streamlines.py, scripts/scil_compute_endpoints_map.py, scripts/scil_evaluate_bundles_individual_measures.py, scripts/scil_normalize_connectivity.py
bundle surface area, irregularity
endpoints-related: surface area, radius, irregularity for each end surface
=> Add bundle measures (area features)

scripts/scil_evaluate_connectivity_pairwise_agreement_measures.py, scripts/tests/test_evaluate_connectivity_pairwise_agreement_measures.py
=> fix_connectivity_pairwise_test

scripts/scil_compute_pft.py
=> Update default step size pft

Jenkinsfile
Also update numpy to 1.20
- Add python3.8 in the future
=> Remove python3.6 from Jenkinsfile

scilpy/segment/voting_scheme.py
Should avoid Command error:
struct.error: 'i' format requires -2147483648 <= number <= 2147483647
=> Reconstruct whole brain on the fly

scilpy/io/image.py, scilpy/preprocessing/distortion_correction.py, scilpy/segment/streamlines.py, scilpy/segment/voting_scheme.py, scilpy/tractanalysis/streamlines_metrics.pyx, scilpy/tractanalysis/todi.py, scilpy/tractanalysis/todi_util.py, scilpy/utils/metrics_tools.py, scilpy/utils/streamlines.py, scripts/scil_analyse_lesions_load.py, scripts/scil_combine_labels.py, scripts/scil_compute_bundle_voxel_label_map.py, scripts/scil_compute_connectivity.py, scripts/scil_compute_kurtosis_metrics.py, scripts/scil_compute_local_tracking.py, scripts/scil_compute_pft.py, scripts/scil_compute_seed_density_map.py, scripts/scil_compute_sh_from_signal.py, scripts/scil_compute_ssst_frf.py, scripts/scil_dilate_labels.py, scripts/scil_run_nlmeans.py, scripts/scil_smooth_surface.py
Change 
* np.int to int
* np.bool to bool
* np.float to float
=> Warning numpy fixed

scilpy/reconst/fodf.py, scilpy/reconst/frf.py, scilpy/reconst/raw_signal.py, scilpy/utils/bvec_bval_tools.py, scripts/scil_compute_dti_metrics.py, scripts/scil_compute_kurtosis_metrics.py, scripts/scil_compute_msmt_fodf.py, scripts/scil_compute_sf_from_sh.py, scripts/scil_compute_ssst_fodf.py, scripts/scil_extract_b0.py, scripts/scil_merge_sh.py
Add overwrite and assert on outputs to extract_b0 and fix typo in scil_merge_sh
=> Modify check_b0_threshold and typo fix

scilpy/segment/streamlines.py, scilpy/tracking/tools.py, scilpy/utils/bvec_bval_tools.py, scilpy/utils/metrics_tools.py
=> Fix numpy warning (round 2)

scripts/scil_visualize_bundles_mosaic.py
Add two options: --no_information and -- light_screenshots (3 views instead of 6)
=> Remove information and add light view

scripts/scil_visualize_connectivity.py
=> fixed help messages to be more clear

scripts/scil_compute_mean_fixel_afd_from_hdf5.py
Crash on empty node since the rd was removed
=> Remove rd from empty return

scripts/scil_filter_tractogram.py
Enhancement to avoid having to dilate mask and atlas manually before filtering.
To facilitate usage it dilate everything the same way.
The enlargement is made in term of voxel, so the provided value is relative to voxel size
=> Add a soft distance to facilitate manipulation

scripts/scil_run_commit.py
Small correction due to misunderstanding + change to COMMIT.
This should force a new hotfix tag/release?  @mdesco
=> Fix: Wrong weights in COMMIT

scripts/scil_compute_asym_odf_metrics.py
One of my smallest PR.
I just updated the reference in `scil_compute_asym_odf_metrics.py` because I realized the abstract number was wrong.
=> [DOC] Minor edit for abstract number in scil_compute_asym_odf_metrics.py

docs/source/documentation/tractogram_registration.rst
=> update doc registration

scilpy/image/resample_volume.py, scilpy/image/reslice.py, scripts/scil_resample_volume.py
Finally I fixed the resampling issue that we had. Now the offset is always ok. I tested it with iso and aniso voxels and worked on my side. Please test it with your own data.
The fix comes from mrtrix resampling script.
=> Fix reslice issue

scripts/scil_compute_qball_metrics.py, scripts/tests/test_compute_qball_metrics.py
Port `scil_compute_qball_metrics.py` from bitbucket.
~~It already works but I need to standardize the arguments parser so it fits with our other scripts.~~
~~Also I will add tests.~~
Closes #441
=> Add scil_compute_qball_metrics.py

scilpy/image/datasets.py, scilpy/tracking/local_tracking.py, scilpy/tracking/seed.py, scilpy/tracking/trackable_dataset.py, scilpy/tracking/tracker.py, scilpy/tracking/tracking_field.py, scripts/scil_compute_local_tracking.py
**Small changes:**
- camel case
- unused variables
- unused imports
- comparison simplification
- missing params in doc
- redundant paranthesis
- etc.
**Big changes:**
- Removed possibility to track for a fixed nbr_streamlines (option ns). Now only available: npv, nt.
- Seed: does not need to be a child of Dataset. Modified. Renamed SeedGenerator.
- BinaryMask: not needed. Deleted, can simply be a Dataset (here renamed AccessibleDataset). Its old function "is_propagation_continues" is now directly computed in the tracker. The only line that is now deleted is the one below. (was it necessary? Add a option in Dataset?): 
```
self.m.data = np.array(self.m.data)
```
**New diagram**
https://docs.google.com/presentation/d/1mvvBYjKZ-IVmkl1EYWBTQ_8T8H0R3_Y-/edit?usp=sharing&ouid=101323301275554058 …
=> Improve code style in (bitbucket-imported) tracking files

scripts/scil_compute_powder_average.py, scripts/tests/test_compute_powder_average.py
As per request from @mdesco a while ago.
Added a script to compute a powder average from a series of diffusion images. Can be used to calculate mean diffusion weigthed image from a single shell or from all diffusion weighted volumes in series.
=> Powder avg

scilpy/io/fetcher.py
Add test data to `processing.zip`.
=> Update processing.zip checksum

scilpy/utils/streamlines.py
Reapply the right dtype (fix for #543 )
=> fix_transform_warp_dtype

scripts/scil_apply_bias_field_on_dwi.py
=> fix_left_out_voxel in apply_bias_field_on_dwi

scilpy/io/utils.py, scilpy/tracking/tracker.py, scripts/scil_compute_local_tracking_dev.py
#531 + @GuillaumeTh answer: "Je dirais que faudrait retirer l'option"
=> remove mmap option

docs/requirements.txt, requirements.txt
=> Update to numpy 1.21.*

scripts/scil_outlier_rejection.py, scripts/tests/test_outlier_rejection.py
Similar to scil_detect_streamlines_loops.py or scil_filter_streamlines_by_length.py.
=> Adding count display in scil_outlier_rejection

scripts/scil_fix_dsi_studio_trk.py
This should make all the data in https://brain.labsolver.org/hcp_trk_atlas.html work!
=> Fix fix dsi studio

scilpy/reconst/bingham.py, scripts/scil_compute_lobe_specific_fodf_metrics.py, scripts/scil_fit_bingham_to_fodf.py, scripts/tests/test_compute_lobe_specific_fodf_metrics.py, scripts/tests/test_fit_bingham_to_fodf.py
Seems like a necessary option to save some precious time.
Let's not waste time fitting Bingham distributions to GM/CSF FODF.
=> Add mask option for bingham fit and metrics

scripts/scil_score_tractogram.py
Small fix in case there were no streamlines in a wpc.
@AntoineTheb
=> Fix case with no wpc in scil_score_tractogram

scripts/scil_streamlines_math.py
Fix case where output is a tck and at least one input was trk: wrong header.
=> Fix lazy usage with tck files

scilpy/io/utils.py, scripts/scil_compute_metrics_stats_in_ROI.py, scripts/scil_verify_space_attributes_compatibility.py
#615 
This may need a little bit more work to make it smooth :)
=> Add a function to verify compatibility

scilpy/segment/tractogram_from_roi.py, scilpy/tractanalysis/scoring.py, scilpy/tractanalysis/tools.py, scripts/scil_score_tractogram.py
Absolutely no changes in this PR. I only copied and pasted methods from the script into files for eventual shared usage with another script. File was becoming big so I splitted the tractometry on bundles from the segmentation of bundles. More changes to come but it will be easier to review if I first move everything without touching them.
=> Moving methods

scilpy/tracking/seed.py
There you go, @CHrlS98 !  Tell me if it works!
=> New method to get n seeds at once.

requirements.txt, scripts/scil_filter_tractogram.py
Add the possibility to use multiple IDs to filter tractogram with an atlas.
=> [ENH] Add multiple ID to filter tractogram with atlas

scripts/scil_assign_custom_color_to_tractogram.py
Optional colorbar image output for `scil_assign_custom_color_to_tractogram.py` script.
Closes #628.
@mdesco
=> `scil_assign_custom_color_to_tractogram.py` optional colorbar image output

scripts/scil_score_bundles.py, scripts/tests/test_score_bundles.py
Smaller PR while waiting for #641
=> Add check_bbox_false (only in scil_score_bundles)

requirements.txt, scilpy/io/fetcher.py
Trying to fix the data fetcher.
After too many downloads, data is blocked. See here, it is a known issue.
https://github.com/wkentaro/gdown/issues/43
Solution based on the discussions in this link.
=> Fix fetcher

requirements.txt, scripts/scil_validate_bids.py
Thanks to @bpinsard I've got access to a highly advanced dwi BIDS structure.
It needs a lit bit more work, but as you can see @AlexVCaron the code should be less cryptic and more efficient.
=> [ENH][BF] scil_validate_bids

README.md, scilpy/version.py
Update the entire repo to Python 3.10
=> Change version number

scilpy/io/fetcher.py
Switch from logging to raise ValueError
=> Reactivate md5sum in fetcher

scripts/scil_compute_local_tracking.py, scripts/scil_compute_local_tracking_dev.py, scripts/scil_compute_local_tracking_gpu.py
#670 
```
mrcalc ~/.scilpy/tracking/seeding_mask.nii.gz 10 -gt ~/.scilpy/tracking/seeding_mask_gt.nii.gz
scil_compute_local_tracking.py ~/.scilpy/tracking/fodf.nii.gz ~/.scilpy/tracking/seeding_mask_gt.nii.gz ~/.scilpy/tracking/seeding_mask.nii.gz t.trk
```
=> fix seed mask empty

requirements.txt, scilpy/io/fetcher.py, scilpy/io/streamlines.py, scripts/tests/test_compute_pca.py, scripts/tests/test_group_comparison.py
To test: 
scil_tractogram_math.py union t0003__in_AC_Cx_f.trk t0003__in_CC_BG_f.trk toto.trk -f
[trk.tar.gz](https://github.com/scilus/scilpy/files/10992916/trk.tar.gz)
=> Update to hotdipy + fix load empty sft

requirements.txt
Upgrade DIPY to latest release and wait on the CI to see how it goes.
=> Upgrade dipy to 1.7.0

scripts/scil_filter_tractogram_anatomically.py
No loop was not working properly
=> Fix filter anatomically

scilpy/io/utils.py, scripts/scil_compute_memsmt_frf.py, scripts/scil_compute_msmt_frf.py, scripts/scil_compute_ssst_frf.py
I created a function the check the roi_radii format. I also updated a bit the help of ssst_frf to be as descriptive as msmt_frf and memsmt_frf.
@mdesco @Manonedde
=> Create a assert_roi_radii_format function for FRF scripts

scripts/scil_compute_memsmt_frf.py, scripts/scil_compute_msmt_frf.py
I removed the frf_table option from scil_compute_msmt_frf and scil_compute_memsmt_frf.
@Manonedde @mdesco
=> Removing frf_table option

scilpy/io/utils.py, scripts/scil_compute_NODDI.py, scripts/scil_compute_freewater.py, scripts/scil_run_commit.py
One fonction removed from 3 scripts and moved to scil.recons.util
pytest test_compute_freewater.py fails on my end...
=> Noddi clean up

scripts/scil_compute_dti_metrics.py, scripts/tests/test_compute_dti_metrics.py
simple line removed. 
Tests pass.
=> Dti clean up

scilpy/image/tests/test_volume_operations.py, scilpy/image/volume_operations.py, scilpy/utils/util.py, scripts/scil_apply_transform_to_image.py, scripts/scil_crop_volume.py, scripts/scil_reshape_to_reference.py, scripts/scil_snr_in_roi.py
Changes done : 
- Test for volume operations module.
- Cleaning of scil_reshape_to_reference and scil_apply_transform_to_image.
- Moving functions out of scil_apply_transform_to_image to utils/util.py.
- Improved docs as much as possible.
=> Adding volume operations tests

README.md, setup.py
For dev purposes, if you don't want legacy scripts to be installed:
```
export SCILPY_LEGACY='False'
pip install -e .
```
=> Legacy installation

scripts/legacy/scil_combine_labels.py, scripts/legacy/scil_compare_connectivity.py, scripts/legacy/scil_compute_connectivity.py, scripts/legacy/scil_dilate_labels.py, scripts/legacy/scil_evalutate_connectivity_graph_measures.py, scripts/legacy/scil_evalutate_connectivity_pairwise_agreement_measures.py, scripts/legacy/scil_filter_connectivity.py, scripts/legacy/scil_normalize_connectivity.py, scripts/legacy/scil_print_connectivity_filenames.py, scripts/legacy/scil_remove_labels.py, scripts/legacy/scil_reorder_connectivity.py, scripts/legacy/scil_split_volume_by_ids.py, scripts/legacy/scil_split_volume_by_labels.py
Oups, we accepted my last pull requests too fast. In my copy-pasts, I did not change the main I was importing.
=> FIX import new main

scilpy/io/utils.py, scripts/scil_search_keywords.py
add the active version of scilpy to logging.info in the add_verbose_arg function
=> [WIP] Add_version_scilpy

.coveragerc, Jenkinsfile, pytest.ini, requirements.txt
Combine with coverage jenkins plugins
=> [ENH] Add coverage

scripts/scil_dwi_compute_snr.py, scripts/scil_dwi_extract_b0.py
Added overwrite option and fixed error for basename of dwi compute snr script.
@arnaudbore
=> Fix basename compute dwi snr

scripts/scil_detect_dwi_volume_outliers.py
Please include a summary of the changes and the related issue(s) or improvement(s).
Please also include relevant motivation and context. List any dependencies that are required for this change if needed.
...
...
=> Fix the script for unequal bval

.github/workflows/test.yml
=> Cancel previous concurrent build

.github/workflows/test.yml
We used the bad event to launch the github workflows.
...
...
=> run workflow on PR head

scripts/scil_dwi_reorder_philips.py, scripts/tests/test_dwi_reorder_philips.py
I added tests for  scil_dwi_reorder_philips.py, to increase our codecov. I had to create the gtab and json files on the fly.
...
...
=> Adding tests to scil_dwi_reorder_philips.py

scilpy/dwi/operations.py, scilpy/dwi/tests/test_operations.py, scilpy/dwi/tests/test_utils.py, scilpy/dwi/utils.py, scilpy/reconst/frf.py, scripts/scil_dwi_apply_bias_field.py, scripts/scil_dwi_detect_volume_outliers.py
Unit tests for the dwi files.
Changes:
- Now the dwi outlier detection takes into consideration the symmetry of b-vectors.
- In compute_dwi_attenuation: instead of dividing by 0 and then removing infinite values (which generates warning) the division by 0 is handled beforehand.
...
=> Unit tests dwi

pytest.ini, requirements.txt, scilpy/denoise/asym_filtering.py, scilpy/denoise/tests/test_asym_filtering.py, scilpy/tractanalysis/todi.py, scripts/scil_bundle_generate_priors.py, scripts/scil_fodf_memsmt.py, scripts/scil_fodf_msmt.py, scripts/scil_fodf_ssst.py, scripts/scil_qball_metrics.py, scripts/scil_tracking_local.py, scripts/scil_tracking_pft.py
=> [ENH] Dipy 1.9

scripts/scil_volume_b0_synthesis.py
Add a short description and a reference to the synb0 script.
...
...
=> Add description and epilog to Synthesis b0

scripts/scil_tractogram_uniformize_endpoints.py, scripts/tests/test_tractogram_uniformize_endpoints.py
=> Fix issue 962

scripts/scil_tractogram_segment_bundles.py
Updating the BundleSeg reference from arXiv to CDMRI 2023.
=> Updating the BundleSeg reference 

.github/workflows/publish_to_testpypi.yml
=> BF github action

scilpy/tracking/propagator.py, scripts/scil_tracking_local_dev.py, scripts/tests/test_tracking_local_dev.py
Add option sub_sphere
...
Using data from pytest
=> Add param sub_sphere to tracking_local_dev

scripts/legacy/scil_recognize_single_bundle.py
=> Fix wrong import in legacy file

scilpy/image/tests/test_volume_operations.py, scilpy/image/volume_operations.py, scripts/scil_volume_distance_map.py, scripts/tests/test_volume_distance_map.py
Simple script to compute the minimum distance between two masks. This could be useful to compute a lesion to bundle distance to create a NIFTI image and then color a bundle.
(The white sphere is a <lesion>, rendered in 3D in MI-Brain, it was initially a binary mask.
...
...
=> Distance map

scripts/scil_fodf_ssst.py
Using specific data I ended up with different voxels size.
...
=> [BF] Fix save FODF add header info from i_dwi

scilpy/tractograms/tractogram_operations.py
Please include a summary of the changes and the related issue(s) or improvement(s).
Please also include relevant motivation and context. List any dependencies that are required for this change if needed.
...
...
=> Keep old space

scripts/scil_tracking_local_dev.py, scripts/scil_volume_resample.py, scripts/tests/test_volume_resample.py
Here is some data to test everything: https://www.dropbox.com/scl/fo/rtchki2wiirwe15buuo4r/ABGJ-7I3l9V2sIZkpTveBBI?rlkey=nmlwq2zpfbf59it8i6m6cr485&dl=0
`scil_volume_resample.py a107__dwi_n4.nii.gz a107__dwi_n4_resampled_w.nii.gz --voxel_size 0.05 --interp lin -v -f`
```
algo=prob
npv=1
step=0.05
theta=20
sub=1
rk=1
min_L=8
max_L=9
scil_tracking_local_dev.py a107__fodf.nii.gz a107_all_SSp-m_LR.nii.gz a107_SSp-m_CC_body-genu_LR_dil1.nii.gz toto.trk  --algo ${algo} --npv ${npv} --step ${step} --theta ${theta} --sub_sphere ${sub} --rk_order ${rk} --min_length ${min_L} --max_length ${max_L} --process 6 -v -f
```
...
=> [ENH] Fix resample local_tracking_dev accepts close iso voxels

scilpy/tractanalysis/fibertube_scoring.py, scripts/scil_fibertube_score_tractogram.py, scripts/scil_fibertube_tracking.py
For the previous PR: Better documentation and enforce forward_only during fibertube tracking.
...
...
=> New Endpoint Scoring - Charles' suggestions

scripts/scil_freewater_maps.py
I added the Amico ref to `scil_freewater_maps.py`.
...
...
=> Adding ref to scil_freewater_maps

.github/workflows/test.yml
=> Fix merge queue

scilpy/stats/matrix_stats.py, scripts/scil_connectivity_pairwise_agreement.py
Sending the main part of script to a function.
Adding more doc
...
...
=> Cleaning the connectivity pairwise agreement script

scripts/scil_tractogram_segment_connections_from_labels.py, scripts/tests/test_tractogram_segment_connections_from_labels.py
=> Small fix (issue 1123)

scripts/scil_tractogram_commit.py
=> Support .tck for commit

scilpy/tractograms/uncompress.pyx
Fixes issue https://github.com/scilus/scilpy/issues/805.
Closes #805 
Streamline voxel coordinates were moved by epsilon in the streamline direction if a coordinate was on the voxel boundary. This failed when the direction was co-aligned with the voxel grid. This PR move the coordinate by epsilon in the perpendicular direction instead.
...
...
=> BF - fixed voxel bundary conditions in uncompress streamlines

scilpy/tractograms/uncompress.pyx
The change introduced in #1098 broke the identification of voxel between control points.
The refactoring with the `for i in range(3)` changed the results. I'm not sure what is going on, but I restored to the previous code structure.
#805 is still fixed. This was donne by removing the direction component line 248-250 and 254-256.
=> BF - fixed intermidiate voxel identification (introduced by #1098)

scripts/scil_viz_bundle_screenshot_mosaic.py
I tried to use this script but the screenshots where flipped (my image was in RAS). So, I added a rotate 180 to fix the issue.
Before fix:
After fix:
=> BF: Rotate screenshots

scripts/scil_labels_combine.py, scripts/scil_volume_stats_in_ROI.py
Issues revealed thank to the nf-mouse_flow project !
...
...
=> Fix mask creation from labels and stats

scripts/scil_bundle_label_map.py
Was crashing if bundle contains only one streamline
...
...
=> [BF] bundle label map

scilpy/image/tests/test_volume_metrics.py, scilpy/image/volume_metrics.py, scripts/scil_denoising_nlmeans.py, scripts/tests/test_denoising_nlmeans.py
Adding some unit tests for file volume_metrics: piesno
- Clarifying that piesno in 4D gives one value per slice (3rd dimension), not per volume.
- In dipy, the loop that we were doing manually in our piesno function is already implemented. Deleted.
=> Add test for volume_metrics

scripts/scil_volume_reshape.py
=> Fix Issue 1143

scilpy/tractograms/streamline_and_mask_operations.py, scilpy/tractograms/streamline_operations.py, scilpy/tractograms/tests/test_streamline_operations.py, scilpy/tractograms/tractogram_operations.py, scripts/scil_bundle_alter_to_target_dice.py, scripts/scil_bundle_label_map.py, scripts/scil_tractogram_remove_invalid.py
By doing so we can now have a way to filter streamlines by the number of points. 
Maybe not the best way to fix this issue #1161 but it does right now.
...
...
=> [ENH][[BF] Change remove_single_point with filter streamlines_by_nb_points

scripts/tests/test_bundle_label_map.py
Let's see!
Should fix the drop of 13% in coverage from last month.
=> Fix usage of os.chdir in test

scripts/scil_freewater_maps.py
=> [BF] Fix Freewater nb_threads

scilpy/ml/bundleparc/attention.py, scilpy/ml/bundleparc/bundleparcnet.py, scilpy/ml/bundleparc/encodings.py, scilpy/ml/bundleparc/predict.py, scilpy/ml/bundleparc/utils.py, scilpy/ml/utils.py, scripts/scil_fodf_bundleparc.py
Downgrade the recommended torch version to 2.1.2 and uniformize message.
...
=> FIX: torch tripwire message

scripts/scil_bundle_label_map.py
add filtering overlap point + nb points
...
...
=> [BF] Improve scil_bundle_label_map add filtering

scilpy/io/fetcher.py, scripts/scil_tractogram_filter_by_roi.py, scripts/tests/test_tractogram_filter_by_roi.py
Thanks to @levje we found an error when using filtering_list with multiple ids with atlas_roi option.
May need some additional test but seems to work.
...
...
=> [BG] tractogram_filter_by _roi - fix filtering_list

src/scilpy/cli/tests/test_viz_tractogram_seeds_3d.py, src/scilpy/cli/tests/test_viz_volume_screenshot_mosaic.py
After PR #1137, I thought I still had work to do to be able to add these two new tests, but it looks like afterall everything was already fixed!
So, just new tests.
=> Add final viz tests (after PR1137)

.github/workflows/test.yml, pytest.ini, src/scilpy/cli/scil_search_keywords.py, src/scilpy/cli/tests/test_search_keywords.py
Please include a summary of the changes and the related issue(s) or improvement(s).
Please also include relevant motivation and context. List any dependencies that are required for this change if needed.
...
...
=> [FIX] Fix issue when testing search keywords

src/scilpy/tractanalysis/distance_to_centroid.py
Please include a summary of the changes and the related issue(s) or improvement(s).
Please also include relevant motivation and context. List any dependencies that are required for this change if needed.
...
...
=> Avoid numerical shenanigans

docs/source/documentation/getting_started.rst, docs/source/documentation/reconstruction/index.rst, docs/source/documentation/scilpy_paper_index.rst, docs/source/documentation/start_to_finish_pipelines/from_raw_data_to_tractogram.rst, docs/source/documentation/start_to_finish_pipelines/index.rst, docs/source/documentation/start_to_finish_pipelines/using_bash.rst, docs/source/documentation/start_to_finish_pipelines/using_nextflow.rst, docs/source/documentation/tractogram_manipulation/index.rst, docs/source/index.rst
Create the whole-pipelines section.
Add figure 1 to Antoine's tutorial.
Fix some doc errors.
=> Doc add section and fix documentation compile errors
