scilpy/reconst/utils.py
scripts/scil_compute_fodf.py
scripts/scil_compute_fodf_metrics.py

Switching old dipy.reconst.peak module to the new one dipy.direction.peak
https://github.com/nipy/dipy/pull/1824

switch old dipy.reconst.peak to dipy.direction.peak

---

scripts/scil_extract_dwi_shell.py

Add a unique function on the shell indices otherwise the script crash on a case like bvals_to_extract="0 1500 1499".

BF: Fix shell indices

---

scilpy/io/streamlines.py
scripts/scil_compress_streamlines.py

Simple transfert of scripts, remove dependency from TractConverter while keeping the lazy_loading/saving feature and tested for python 3

Futurize streamlines compression

---

scripts/scil_streamlines_math.py

Correction of a typo in input[0] when it should have been inputs[0]

Add s to input from args

---

scilpy/io/utils.py
scripts/scil_remove_invalid_streamlines.py

New scripts to remove streamlines that are invalid in vox space

Remove invalid streamlines (out of bbox)

---

scilpy/io/streamlines.py
scilpy/io/utils.py
scripts/scil_compute_todi.py
scripts/scil_convert_tractogram.py
scripts/scil_filter_tractogram.py
scripts/scil_recognize_single_bundle.py
scripts/scil_remove_invalid_streamlines.py
scripts/scil_streamlines_math.py

Following JC comment PR42 
load_tractogram_with_reference is now in `scilpy/io/streamlines.py`

Move tractogram function to io streamlines and typo

---

scilpy/utils/filenames.py
scilpy/utils/streamlines.py

Make `utils` docstrings' style be consistent: stick to the NumPy/SciPy
style.

STYLE: Make `utils` docstrings' style be consistent

---

scripts/scil_visualize_bundles_mosaic.py

The font was really small on my screen for the mosaic of the bundles.
As is, the script does not consider the arg "font size" if no font name was given, but it is not explained in the -h help.
I added a try: exception that tries to find a truetype font on the computer. This way you don't have to remember where the fonts are everytime you want to use the script and change the size. Should work on most linux versions. Else, explains that it can't and uses default, like before.

Improving font of mosaic

---

.gitignore
requirements.txt
scilpy/io/streamlines.py
scilpy/io/utils.py
scilpy/tractanalysis/__init__.py
scilpy/tractanalysis/features.py
scilpy/tractanalysis/quick_tools.pyx
scilpy/tractanalysis/tools.py
scilpy/tractanalysis/uncompress.pyx
scripts/scil_compute_connectivity.py
setup.py

This is the first working version of a connectivity script.
It finds the longest GM-GM regions connected by each streamline. Cuts to make sure the streamlines really stay in the regions.
Applies optional post-processing steps: length pruning, loop removal, outlier rejection.
It creates a connectivity matrix, and saves the final bundles. It can optionally save raw connections and intermediate files.
NOTE: there are still a few TODOs that could be improved in future versions.
NOTE: There are TODOs that are related to adding other methods to compute values to assign to the connectivity matrix, such as mean FA, etc. It was decided that this could be added later on in the process.
@mdesco anything else you wanted in this first version?
To be able to use this, you will need to run
```
python …
```

Connectivity script

---

scripts/scil_mask_math.py

Small bugfix to `scil_mask_math.py`. If a threshold of zero is given, it is ignored (e.g. when converting a probabilistic map to a binary mask).

BF: Fixed scil_mask_math.py ignoring zero threshold

---

scripts/scil_screenshot_bundle.py
scripts/scil_screenshot_dti.py

Transfert of the scripts, adapted to dipy 1.0.
Switched the template to any mni152 for simplicity for dti and bundle screenshot
The visualisation is now all in rasmm, meaning the mni152 template can be cropped or resampled and it will work.
Added the local_coloring option and the reference coloring now support any colormap instead of the default JET.
data for testing:
https://drive.google.com/open?id=1imRdCPI0KTymLw7TEKSEjkfVqt9s_5lk

Futurize bundle screenshot

---

scripts/scil_count_streamlines.py

Count streamlines now handle tck file correctly and crash for unknown file format.
Only support trk and tck for lazy loading purpose and crash otherwise.
Uniformize the argparser at the same time (args.tractogram -> args.in_tractogram)

Fix count_streamlines to support tck file

---

scripts/scil_filter_tractogram.py

This PR will help speedup pipelines/scripts that use a lot of scil_filter_tractogram.py to extract streamline count.
@mdesco can you check if the help (section display_count) is clear?

Add more outputs to filter tractogram

---

scilpy/io/utils.py
scripts/scil_clean_qbx_clusters.py
scripts/scil_compute_qbx.py

Transfert of QBx script (private bitbucket) and script for clusters cleaning (personal repo).
The QBx script split a tractogram or bundle into clusters (into a directory)
The cleaning script is similar to a MarcAlex script (but simplified) that iterate over a list of clusters and each can be rejected or accepted (useful for BST and RBx model preparation)

Qbx clustering and cleaning

---

scilpy/image/utils.py
scilpy/utils/bvec_bval_tools.py
scripts/scil_extract_dwi_shell.py

- Encapsulated `scil_extract_dwi_shell.py` in `utils/bvals_bvecs_tools.py`
- I was unsure where to put this, maybe this could be moved elsewhere?
- Moved a volume block iterator to `image/utils.py`
- Tested on HCP data

Encapsulate scil_extract_dwi_shell.py

---

requirements.txt
scripts/scil_screenshot_bundle.py

The script was made to simplify screenshot of bundles so the alignment is the same across datasets.
However, if datasets were already in MNI152, the script was slowed down by registration (useless).
Now the --target template is optional.
Since screenshot were designed to be in MNI152, this visualisation is available and @mdesco said he like it. It is now performed at the end (very quick) with basic/common parameters.
https://nilearn.github.io/modules/generated/nilearn.plotting.plot_glass_brain.html

Optional registration for bundle screenshot

---

scilpy/io/streamlines.py
scilpy/io/utils.py

reorganize import on module io

---

scilpy/preprocessing/distortion_correction.py

reorganize import in preprocessing

---

scilpy/reconst/raw_signal.py

reorganize import in reconst

---

scilpy/tracking/tools.py

reorganize import in tracking

---

scilpy/version.py

reorganize import in viz

---

scilpy/tractanalysis/features.py
scilpy/tractanalysis/reproducibility_measures.py
scilpy/tractanalysis/tools.py

reorganize import in tractanalysis

---

scripts/scil_summarize_bundles_similarity_measures.py

When using a single comparison (two subjects) the function ouput a np.float64 and this is not serializable by json. Simple fix to convert to actual float.

Fix serialisation error from np.float64

---

scilpy/io/utils.py

Added a check for "assert_outputs_exist", it test of the directory for the output file exist.
Since most our script assume that the folder for the output file exist, only few of them test it.
I think the default should be "check_dir_exist=True", however it would change the current behavior if so.
This could be move to annother function if prefered, eg
"assert_outputs_directories_exist(...)"
@GuillaumeTh  @jchoude  @frheault

 added a test to check if output folder exist

---

scilpy/version.py

Fix version normalization warning.
Fixes:
```
$ python setup.py install_scripts
/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/setuptools/dist.py:397:
UserWarning: Normalizing '0.1.dev' to '0.1.dev0'
normalized_version,
```
reported when running `setup.py`, e.g. in our CI builds:
https://travis-ci.org/github/scilus/scilpy/jobs/662482838#L1283

ENH: Fix version normalization warning

---

scilpy/tractanalysis/reproducibility_measures.py

I was 100% sure I fixed it weeks ago, but I think I either forgot about it or I made a mistake somewhere.
Anyway, very small error. This code was not used by anyone for any project, so nothing to re-processed. The results were dice around 0.000001 rather than around 0.5-0.9.

Fixing the numerator

---

scilpy/utils/streamlines.py
scripts/scil_apply_transform_to_tractogram.py
scripts/scil_apply_warp_to_tractogram.py
scripts/scil_remove_invalid_streamlines.py

Applying transformation to tractograms can lead to invalid streamlines (out of
the bbox), three strategies are available:
- default, crash at saving if invalid streamlines are present
--keep_invalid, save invalid streamlines. Leave it to the user to run
scil_remove_invalid_streamlines.py if needed.
--remove_invalid, automatically remove invalid streamlines before saving.
Should not remove more than a few streamlines.
The scil_remove_invalid_streamlines.py can now handle single point streamlines if desired.
Both of these enhancements were required for Kurt project, which is a nice large scale use case.

Improved the handling of invalid streamlines

---

scilpy/image/operations.py
scilpy/io/utils.py
scilpy/tractanalysis/reproducibility_measures.py
scripts/scil_compute_connectivity.py
scripts/scil_connectivity_math.py
scripts/scil_decompose_connectivity.py
scripts/scil_normalize_connectivity.py
scripts/scil_summarize_bundles_similarity_measures.py
scripts/scil_visualize_connectivity.py
scripts/tests/test_normalize_connectivity.py

For Sami's project, we needed a script to normalize connectivity matrices.
Some of the options could be achieved through multiple calls to `scil_connectivity_math.py`, but not all (i.e `parcel_volume` and `parcel_surface`)
Other scripts have been modified to handle the usage of logarithm correctly (Around 0) and to make it easier to load/save connectivity matrices. Now that there are more 3-4 scripts related to connectivity, some refactoring was required to avoid duplicated code.
Minor modification to scil_compute_connectivity.py and scil_visualize_connectivity.py (scripts typically being called before and after so they work well together for Sami's project)
These scripts will likely be modified in the future, right now it is being designed with only two projects in mind as an example use …

Normalize connectivity scripts

---

scilpy/io/utils.py
scripts/scil_filter_connectivity.py
scripts/tests/test_filter_connectivity.py

Script to facilitate filtering of connectivity matrices.
The same could be achieved through a complex sequence of `scil_connectivity_math.py`.
For example, a simple filtering (Jasmeen style) would be:
```
scil_filter_connectivity.py out_mask.npy
--greater_than */sc.npy 1 0.90
--lower_than */sim.npy 2 0.90
--greater_than */len.npy 40 0.90 -v;
```
This will result in a binary mask where each node with a value of 1 represents
a node with at least 90% of the population having at least 1 streamline,
90% of the population is similar to the average (2mm) and 90% of the
population having at least 40mm of average streamlines length.
Testing data:
https://drive.google.com/file/d/1o51lTV_ek_cib303ANQMsegxDiZD9kwa/view?usp=sharing

Connectivity filtering from population

---

scripts/scil_screenshot_bundle.py
scripts/scil_visualize_bundles_mosaic.py

Addition for Kurt's project and useful in general.
This script can now handle (in any resolution) binary nifti file. It can even be mixed with tck/trk !
Exact same behavior as before for default usage. The mosaic was printing the number of streamlines, the text was replaced with _elements_ to handle printing number of voxels for masks and number of streamlines for tractograms.
Two very simple coloring option were added uniform_coloring (e.g [1,1,0] for yellow) and random_coloring that assign a random color for each bundle.
Default is endpoints coloring for bundles and white surface for binary mask.
Example image (mask and streamlines, random coloring)

Mosaic bundles support binary nifti

---

scilpy/utils/streamlines.py
scripts/scil_apply_transform_to_tractogram.py
scripts/scil_apply_warp_to_tractogram.py
scripts/scil_remove_invalid_streamlines.py

Here is a small addition to `scil_remove_invalid_streamlines.py` that will cut streamlines that are out of the volume bounding box (and remove the streamline if it is 100% out). It is optional with `--cut_invalid`, however it could be argued that it should be our default.
In order to keep the data_per_point on the rest of the streamline, I am not resampling or using a line-based strategy. This will simply remove the entire segment if one of their points is out. So if the step-size is 10mm, and the segment is out of the bounding box by 1mm it means the 9mm that is perfectly valid will be removed too.
This is only a slight upgrade from removing the entire streamline.
[tiny_test_cut_PR.zip](https://github.com/scilus/scilpy/files/4595447/tiny_test_cut_PR.zip)

Added the cut options for streamlines

---

scripts/scil_apply_transform_to_tractogram.py
scripts/scil_apply_warp_to_tractogram.py
scripts/scil_remove_invalid_streamlines.py

Solves bug (Max) with SET output for Sami's project.
`ValueError: Shape of array too small to calculate a numerical gradient, at least (edge_order + 1) elements are required.`

Skip indices with single points

---

scripts/scil_apply_bias_field_on_dwi.py

This script was taking more than 32GB of RAM on HCP data, so I switch to an approach with masking as early as possible and chunks.
This reduced by a factor 4-5 the amount of RAM needed when not using a mask and 2-3 (at least) when using one.
Otherwise, same behavior as before.

Reduce ram usage in bias field correction

---

scripts/scil_run_commit.py

Will allow saving some time on kernel computation on data with complex acquisition scheme (like HCP) in the Connectoflow pipeline. On a simpler dataset, it does not save much (but at least it does cost much).
Also, the original code was not using the tracking_mask properly due to a default parameter being `use_mask=False`
Tested using connectoflow on Sami's Data

Compute kernel only

---

scilpy/io/fetcher.py
scripts/scil_run_commit.py
scripts/scil_visualize_connectivity.py

This is an update for my first try running connectoflow on 105 HCP subjects.
Some stuff went wrong in COMMIT:
Following discussion with Ale I changed the default param for perp_diff and fix a bug due to bad normalization when close to zeros voxel where present.
Tiny fix in visualize_connectivity to support negative values and exclude zeros (more robust for connectoflow)
Also fix an error in the test fetcher (probably due to a previous merge error on my part)

Remove normalisation COMMIT

---

scripts/scil_compute_ssst_frf.py

WM mask argument was not extracted properly from argparser
Data: https://drive.google.com/drive/folders/1CeKuVZZCbLSgZK1BI6kv9Plg6yzO7VXL?usp=sharing
`./scripts/scil_compute_ssst_frf.py fibercup_dwi.nii.gz fibercup_dwi.bvals fibercup_dwi.bvecs frf.txt --min_fa 0.10 --mask_wm fibercup_wm.nii.gz -f`

FIX: WM mask argument in scil_compute_ssst_frf.py

---

scripts/scil_save_connections_from_hdf5.py

Add the options to save with specifying edges_keys of interet or with node_keys to the script save_connections_hdf5.py.
Data from the scirpt decompose_connectivity is avalaible here : [(https://drive.google.com/file/d/1cavj1VGavbPJCBbPdAN9dqz845Tza-tN/view?usp=sharing)].

Adding saving options to save connectivity

---

scilpy/segment/streamlines.py
scripts/scil_filter_tractogram.py

If _any_ meant _any_ part of the streamline must be in the mask, _all_ means that _all_ part of the streamline must be in the mask.
When used with _exclude_, it means that a streamline entirely in the mask will be excluded. Using _all_ it with x/y/z plane works but makes very little sense.
In terms of nifti mask, `--drawn_roi MASK.nii.gz all include` is equivalent to `--drawn_roi INVERSE_MASK.nii.gz any exclude`
For example, this allows to find out all streamlines entirely in the WM in one command (without manually inverting the mask first) or to remove any streamlines staying in GM without getting out.
Simple quick test, take one streamline from a tractogram, create a binary map from that streamline and take it out from the tractogram with `--drawn_roi …

Added 'all' options for tractogram filtering

---

README.md

A simple addition of the instructions for MacOS (more of an advice, since not everyone uses `brew`)

Add blas/lapack instruction for Mac

---

scripts/scil_recognize_single_bundle.py

A simple fix for a warning that annoys me (using `from_sft` in dipy 1.2 will be better)

Remove sft as reference

---

requirements.txt
scilpy/image/operations.py
scripts/scil_connectivity_math.py
scripts/scil_image_math.py
scripts/scil_split_tractograms.py
scripts/scil_split_volume_by_ids.py
scripts/scil_split_volume_by_labels.py
scripts/tests/test_image_math.py

Resolving issue #235 
I thought that a heuristic was not a robust/useful approach to common operations I know are possible (e.g adding 100+ labels in in16) so I modified all operations so they could be performed on the fly one image at the time.
This does not affect the speed in an observable way below 10 images, slightly slower than before above 25-50. To my surprise, since `AverageImages` is multiprocessed (1 main CPU and multiple readers) `scil_image_math.py ` is actually faster in CPU-times! So I think it's fine just like that.
Before all operations were capped at around 100 3D images in float32, now I can call any operation with hundreds of images!
Operations such as concatenate (of 3D images still rely on 4D image routine so this one have the same limitation as before
Operations …

Memory friendly scil_image_math.py

---

scripts/scil_prepare_eddy_command.py
scripts/scil_prepare_topup_command.py

Added cmd, switch default to empty string instead of none

Fix scil_prepare_* so empty options does not crash

---

scilpy/tractanalysis/uncompress.pyx

Remove useless get_data for size estimation, this is only done to know the nbr of point.
But since nibabel 3.0 the `get_data()` function return a copy which takes times AND memory.
Since at this step the tractogram are (typically) between 1-3Go, this is a substantial spike in memory.
All to simply know the shape of an array. `._data` is not safe for modification, but to do a `.size` it is fine.

Remove get_data for size estimation in uncompress

---

scripts/scil_decompose_connectivity.py
scripts/scil_remove_invalid_streamlines.py

While processing a lot of data, I realized that sometime the decompose would produce an invalid streamline during the cutting portion. An infinitely small step for example, combine with the cast to float16 this produced overlapping point and then crash in cython code such as  grid_intersection.
This happened with like 10 streamlines over 100 HCP subject, so super rare. Yet I observed it. So here is a small fix to remove invalid right before saving, and reverted to float32 in case.

FIX - Robustness in decompose due to invalid streamlines

---

scripts/scil_reorder_dwi_philips.py

Fix the reordering saving of the diffusion to have the exact same header. Tested with Myelo-Inferno and Penthera3T.

Fix saving for reordering

---

containers/Dockerfile

Fixed the mpl backend setup for the Docker container, to avoid issues such as crashing when plotting the residuals figures in scil_compute_dti_metrics.py

BF: fixed Matplotlib backend in dockerfile

---

requirements.txt
scilpy/version.py
setup.py

Change the version number, adapted requirements for centOS (clusters or Linux Kernel in Bordeaux)
The change to VTK will always take the highest available version (which is currently 8.1.* on centOS and 9.0.* on Ubuntu)

Change version

---

requirements.txt
scripts/scil_normalize_connectivity.py

Sami had 4 subjects with label 90 with 0 voxels in them after warping to MNI.
Maybe sign of an issue but regardless, we should deal with the case label is empty. The volume normalization was doing this check but not the surface normalization.
This should fix it.
Data to test: https://www.dropbox.com/s/kuwb5lhs8339x5v/normalization_fix.zip?dl=0
Command ran:
scil_normalize_connectivity.py sc.npy sc_surface_normalized.npy --parcel_surface atlas_brainnetome_v2_mni.nii.gz brainnetome_mni.txt

scil connectivity Normalization fix by zero labels

---

scripts/scil_visualize_connectivity.py

(duplicate from old PR344 but with clean history)
Bug detected by Sami with non-square connectivity matrices.
To test this:
https://www.dropbox.com/s/ge4qpxi8934sbt5/PR_BF_reorder.zip?dl=0
Try these 2 commands:
scil_reorder_connectivity.py sc.npy test_short.txt --labels_list atlas_brainnetome_v2_labels_list_final.txt --out_suffix _reordered -f
scil_visualize_connectivity.py sc_reordered.npy sc_reordered.png --labels_list atlas_brainnetome_v2_labels_list_final.txt --reorder_txt test_short.txt --name_axis --axis_text_size 4 4 --display_legend -f

BF (bug fix) reorder visualize connectivty 

---

scripts/scil_visualize_bundles_mosaic.py

FIX scil_visualize_bundles_mosaic.py: Intermediate thumbnail screenshot saving was crashing because no extension was specified. 
Testing data: https://drive.google.com/drive/folders/1wlfTUqPW3W5r6nkGQXXqTkvneaFeCy9W?usp=sharing
@arnaudbore @GuillaumeTh @frheault

FIX: scil_visualize_bundles_mosaic.py crash

---

scilpy/viz/chord_chart.py
scripts/scil_visualize_connectivity.py
scripts/tests/test_visualize_connectivity.py

Added options for visualization of connectivity, chord chart!
This is very hard to do in matplotlib (or even in fancy library like Plotly), I used some code I found online and modified it to our need.
This option works best with matrix containing around 25-250 connections, more than that and it requires heavy fine-tunning for it to look nice (likely not possible with the scripts).
It also has some difficulties if the biggest connection is 10x higher values than the second or weird extreme distribution.
Otherwise it works pretty well.
Only makes sense for streamlines count and volume matrix, does not make sense with length or FA.
https://drive.google.com/file/d/1Zka8-xmb1xwJGT7QRW4NRO3LaQIkk3W6/view?usp=sharing

Chord chart connectivity

---

scripts/scil_evaluate_bundles_pairwise_agreement_measures.py
scripts/tests/test_evaluate_bundles_pairwise_agreement_measures.py

Add tractometer-style overlap and overreach output as a ratio over the "gold-standard" instead of absolute values.
@arnaudbore @frheault @GuillaumeTh

ENH: Add ratio to pairwise_agreement

---

scilpy/io/image.py
scilpy/segment/recobundlesx.py
scilpy/segment/voting_scheme.py
scripts/scil_recognize_multi_bundles.py

I realized I was generating all of thousands of parameters combinations AND including the models bundle in it. Meaning that if you run 18 parameters * 5 models * 2 seeds you are copying the model bundles that many times in memory before launching sub-processes. Oversight on my part, also I realized that copies (as many as # thread) of QBX indices was kept during the sub-processes despite not being needed for the whole time, so now it is deleted.
These two additions save quite a lot of RAM, enough that now I am fairly sure RBx can be run on the 192Gb node at 40 CPU !
Other tiny fixes on the side, I can explain if needed.

Update to save RAM and parameters optims

---

scilpy/io/streamlines.py

Add a warning when loading a .trk with a reference that the reference will be discarded. `scilpy.io.streamlines.load_tractogram_with_reference` was pulling a sneaky and discarding the reference without telling the user if the tractogram was a .trk. Atleast the user should be told that the reference is discarded.
@frheault @GuillaumeTh @arnaudbore

FIX: Add warning to reference and .trk

---

scripts/scil_evaluate_bundles_pairwise_agreement_measures.py
scripts/tests/test_evaluate_bundles_pairwise_agreement_measures.py

As mentioned in #361 the current behavior was not intuitive and maybe oriented too much toward my own use (from Tractostorm). So I add a parameter to allow to switch from one the other directly in the script.

Optional overlap in pairwise measures

---

scilpy/io/streamlines.py
scripts/scil_visualize_bundles_mosaic.py

- Add reference to `scil_visualize_bundles_mosaic.py`
- Add check that `--reference` is in args
Fixes #386 
@arnaudbore @frheault @GuillaumeTh 
Tests are running, will update once they're done

FIX: Add reference to mosaic and check reference

---

scilpy/reconst/raw_signal.py

Hi,
I changed the call to `sf_to_sh` in `scilpy/reconst/raw_signal.py` to respect the new DIPY 1.3 method signature, which is:
```
sf_to_sh(sf, sphere, sh_order=4, basis_type=None, full_basis=False, legacy=True, smooth=0.0)
```
Otherwise, the value of variable `smooth` is used for `full_basis` argument, and since it is not 0 by default, `sf_to_sh` returns coefficients for a full SH basis.
@arnaudbore

BF: Fix scil_compute_sh_from_signal uses full SH basis by default

---

scilpy/utils/image.py
scripts/tests/test_reshape_to_reference.py

Hi,
When reshaping a 4D volume, `scil_reshape_to_reference` crashes because an unknown keyword argument is passed to `utils.image.transform_dwi`. I fixed it and added a test case to validate.
Thanks!

BF: Fix scil_reshape_to_reference crashes with TypeError

---

scripts/scil_compute_msmt_frf.py
scripts/scil_compute_ssst_frf.py
scripts/tests/test_compute_msmt_frf.py
scripts/tests/test_compute_ssst_frf.py

Quick fix of the `--roi_center` argument for `scil_compute_ssst_frf.py` and `scil_compute_msmt_frf.py`. It was missing `nargs=3` so it could not actually be used. I added `--roi_center` to the tests of these scripts so a quick pytest should do it.

Fixing roi_center argparser

---

scripts/scil_evaluate_bundles_pairwise_agreement_measures.py

Process pool may have not been initialized if `single_compare` was used.
@frheault @arnaudbore @GuillaumeTh

FIX: Process pool bug in `scil_evaluate_bundles_pairwise_agreement_measures`

---

scripts/scil_visualize_bundles.py

As title says. Default coloring (by fury-gl) remains to compute a single color for each streamlines based on its endpoints
If you have the rbx atlas downloaded, you can test with:
Local coloring:
`$ ./scripts/scil_visualize_bundles.py atlas/**/* --local_coloring --width=0.35 --subsample 5`
Uniform coloring:
`$ ./scripts/scil_visualize_bundles.py atlas/**/* --width=0.35 --subsample 5 --uniform_coloring 50 100 85`
Default coloring:
`$ ./scripts/scil_visualize_bundles.py atlas/**/* --width=0.35 --subsample 5`
@arnaudbore @frheault @GuillaumeTh

ENH: Add local orientation and uniform coloring to `scil_visualize_bundles`

---

scripts/scil_compute_connectivity.py
scripts/scil_merge_json.py

Slightly clearer error when an empty matrices is produces. This should never happen, which is why it crash.
An empty matrices means there is no single streamlines in the input decomposed. If you reach compute connectivity with this it is worthy of an error.

Empty h5 compute connectivity

---

scripts/scil_compute_freewater.py

After several tests on multiple databases (ADNI, PPMI, myelo-inferno, ...), I come to the conclusion that lambda2 default should be a little higher.

FW_default minor change

---

scripts/scil_run_commit.py

Following a discussion with Ale, COMMIT2 parameters had to be fine-tuned as well as the output normalized.
@mdesco This should cover what we talked about.
Overall, this simply reduce the tolerance of COMMIT1 if COMMIT2 is about to be run.
Also, the raw commit weights per streamline had to be weighted by the streamline length.

Update parameters of commit1/commit2

---

scripts/scil_evaluate_bundles_binary_classification_measures.py
scripts/scil_perform_majority_vote.py

This simply avoid double loading and iteration over all streamlines (using array and numpy for vote instead)

Perform majority vote refactor (faster/clearer)

---

scripts/scil_compute_sf_from_sh.py
scripts/tests/test_compute_sf_from_sh.py

- Compute SF on a sphere from an SH signal (ODF or fODF)
- Can provide the sphere as argument (currently symetric724 or repulsion724)
- Original b0s are concatenated to have a coherent volume for further analysis

Add compute_sf_from_sh.py script

---

scilpy/image/operations.py
scripts/scil_filter_connectivity.py

In relation to #385 . This add new condition to image_math and connectivity math
- lower_threshold -> lower_threshold_eq
- upper_threshold -> upper_threshold_eq
The >= and <= are not clearly distinct.
The script scil_filter_connectivity was unclear. The greater_than and lesser_than option were actually greater_or_equal and lesser_or_equal. To make it clearer, while keeping the script easy to read (and simple) the equals were removed and now the script does what the paramters are saying. Strictly greater or lesser than.
@mdesco This should be slightly clearer

Clarification to condition for greater or lesser than

---

scilpy/reconst/multi_processes.py
scripts/scil_compute_sf_from_sh.py
scripts/tests/test_compute_sf_from_sh.py

Using Dipy's `sh_to_sf` caused memory problems because everything is computed in float64. I refactored the code to work like `convert_sh_basis`, so it can run in parallel, and I use float32 to make it fit in memory, especially when working with 1x1x1 volumes with > 200 SF directions.

Refactor scil_compute_sf_from_sh.py

---

scilpy/image/resample_volume.py
scilpy/image/reslice.py
scripts/scil_resample_volume.py
scripts/tests/test_resample_volume.py

`scil_resample_volume` now handles resampling to arbitrary resolutions. Will be useful for future multi-resolution tracking.
Also fixes a bug with the offset of resampled volumes. "Old" behavior is still available through the `zoom` argument.
Test data: https://drive.google.com/file/d/1k0vqk4tp5y0q3SRGOtU2esY2a8h0zGT8/view?usp=sharing
To test:
`$ scil_resample_volume.py Simulated_FiberCup_fodf_6.nii.gz Simulated_FiberCup_fodf_6_32_32_3.nii.gz --resolution 32 32 3 -f`
Downsamples the fibercup from 64x64x3 to 32x32x3
@arnaudbore @frheault @GuillaumeTh @mdesco

ENH: Resample volume to resolution

---

scripts/scil_score_tractogram.py

Fix bug if GT bundles are `.tck`. Same reference is used for both the bundle to be scored and the GT bundles as they should be in the same space anyways (else scoring won't work).
PR test data: 
```
scil_score_tractogram.py prob_5_seeds.tck \
~/braindata/databases/fibercup/simulated/MICCAI2015/tracking/FiberCupGroundTruth_filtered_bundle_* \
--gt_heads ~/braindata/databases/fibercup/simulated/MICCAI2015/scoring_data/masks/rois/FiberCupGroundTruth_filtered_bundle_*_head.nii.gz \
--gt_tails ~/braindata/databases/fibercup/simulated/MICCAI2015/scoring_data/masks/rois/FiberCupGroundTruth_filtered_bundle_*_tail.nii.gz \
--dilate_endpoints 1 \
--reference ~/braindata/databases/fibercup/simulated/MICCAI2015/scoring_data/masks/wm.nii.gz -f 
```
Fixes #460 
@arnaudbore @GuillaumeTh

FIX: Fix GT bundle reference in scoring

---

scilpy/tractanalysis/todi.py
scripts/scil_generate_priors_from_bundle.py

Fix a bug where the TODI computation might crash. Also add `--reference` arg in `scil_generate_prior_from_bundle`
Behavior before:
How to test:
```bash
$ scil_generate_priors_from_bundle.py low.tck mid.nii.gz mid_wm.nii.gz -f
```
Test data: https://drive.google.com/drive/folders/1P4TsS-ESvhbIIf_U_Y-_WAchEmlTfNwz?usp=sharing
@arnaudbore @GuillaumeTh

FIX: TODI chunk-size bug + reference arg

---

scilpy/image/utils.py
scilpy/utils/bvec_bval_tools.py
scripts/scil_extract_b0.py

This PR contains modifications to :
- Extract b0 : added more extraction options, such as extracting b0s from clusters of b0s in the data (mean or first b0 of each cluster). Also reformatted the code to enable lazyloading. (Does not modify previous behavior of the script, fully back-compatible cli)
- Prepare Topup : TBD
- Prepare Eddy : TBD

[ENH] Extend extract_b0 capabilities

---

requirements.txt

- Fixes error : `ModuleNotFoundError: No module named 'cvxpy.cvxcore.python._cvxcore'
During handling of the above exception, another exception occurred:
RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd`

Update numpy version for CVXPY

---

scripts/scil_run_commit.py

Adressing comments from Simona:
Regarding the information in the help of scil_run_commit.py I would change
**1)**
```
- compartment_EC.nii.gz (Extra-Cellular)
- compartment_IC.nii.gz (Intra-Cellular)
- compartment_ISO.nii.gz (isotropic volume fraction (freewater comportment))
```
in
```
- compartment_EC.nii.gz (estimated Extra-Cellular signal fraction)
- compartment_IC.nii.gz (estimated Intra-Cellular signal fraction)
- compartment_ISO.nii.gz (estimated isotropic signal fraction (freewater comportment))
```
**2) The lines**
```
- commit_weights.txt
Text file containing the commit weights for each streamline of the
input tractogram.
```
appear 2 times. Also are you sure you want to modify them from the name in the orignal code (which is streamline_weights.txt)? This would mean that running …

Simona's comments about COMMIT

---

requirements.txt
scilpy/utils/transformation.py
scripts/scil_fix_dsi_studio_trk.py
scripts/scil_flip_streamlines.py
scripts/tests/test_fix_dsi_studio_trk.py

After some time I gathered enough DSI-Studio corner case data to find exactly how to fix them.
Its working perfectly on 1 datasets from Leon C., 1 from Kurt S., HCP, old surgery case from Sherbrooke and the TractEM (BLSA) data
There is at least 2 thing wrong with the TRK header, 2 thing wrong with the TRK data, 1 thing wrong with the NIFTI and the NIFTI is moved to AC-PC.
That 4 things to fix to get it aligned with itself in MI-Brain and 2 more step to get to "native space'' (including rigid registration).
I can't garantee its perfect, but I think its close to it. If the data does not have too much skull and voxels smaller than 2mm iso, its pretty robust.
In summary:
1. Read the tractogram with nibabel API
2. Shift the origin by 1 voxel in X and Y
3. Flip tractogram in X/Y around its …

fix_dsi_studio_trk

---

scilpy/preprocessing/distortion_correction.py
scripts/scil_prepare_eddy_command.py
scripts/scil_prepare_topup_command.py

Modifications to prepare_topup :
- Handles b0 images composed of multiple forward and reverse phase acquired volumes
- Added parameter to change the name of the acquisition parameters file outputed
- IMPORTANT : the script does not accept a DWI as input for the forward acquired image, only a b0 volume. Users must handle the extraction of the b0s using scil_extract_b0
Modifications to prepare_eddy :
- Added logic to handle the different sizes of b0 images that Topup ran on
- Added parameters to input the number of reverse phase volumes present in the input DWI image
- Added parameter that takes a acquisition parameters file as an input, required to know the number of b0 volumes to take into account when creating the index file
-  Added parameter to get least-square resampling outputs when …

[ENH] Add capacities to prepare Topup and Eddy

---

scripts/scil_compute_todi.py

Hi!
I was playing with scil_compute_todi on a Fibercup phantom with big voxels (6 mm) and noticed what appears to be an offset between the tractogram and the TODI output. This is shown in the screenshot from MI-Brain below.
Because `compute_todi` expects the voxel origin to be in the corner rather than at the center of the voxel, calling `stateful_tractogram.to_corner()` in `scil_compute_todi.py` results in the following.
Is this a good enough fix or am I missing something?
Thanks!

[BF] scil_compute_todi output misaligned with tractogram

---

scilpy/utils/streamlines.py
scripts/scil_compute_bundle_voxel_label_map.py

RBx-Flow does not output empty bundle, so it works well with Tractometry-Flow
However, bundles from other sources could be empty.
These minimal changes allow the pipeline to execute the same way if a bundle is just not there or if it is there, but empty.

Support empty bundle in tractometry

---

scilpy/tractanalysis/scoring.py
scripts/scil_score_tractogram.py

So I was trying out `scil_score_tractogram.py`.
I get a crash when scoring the ground truth tractogram on itself, because there are no false connections. I added a case for when the tractogram minus the true connections is empty to prevent crashing. Also, I added a check to not save the nc tractogram when it is empty.
@AntoineTheb If I remember correctly you worked quite a lot on this script, does the fix look ok?

[BF] Bug fix for when there is only tc when scoring tractogram

---

scilpy/utils/streamlines.py
scripts/scil_apply_transform_to_hdf5.py
scripts/scil_apply_transform_to_tractogram.py
scripts/scil_fix_dsi_studio_trk.py

Following an issue raised by @StongeEtienne (Sorry I forgot about it), this allows for a more intuitive usage of the transform script.
TestingData:
https://drive.google.com/file/d/1VcTaBS_eCfze4tmM7cpliTYyJ6S6Bp0i/view?usp=sharing
It is still very hard to know what it's doing for anyone not familiar with the convention.
```
Example:
To apply transform from ANTS to tractogram. If the ANTS commands was
MOVING->REFERENCE, this will bring a tractogram from MOVING->REFERENCE
scil_apply_transform_to_tractogram.py ${MOVING_FILE} ${REFERENCE_FILE}
0GenericAffine.mat ${OUTPUT_NAME}
--inverse
--in_deformation 1InverseWarp.nii.gz
If the ANTS commands was MOVING->REFERENCE, this will bring a tractogram
from REFERENCE->MOVING
scil_apply_transform_to_tractogram.py ${MOVING_FILE} ${REFERENCE_FILE} …
```

Add inverse operation flag

---

scilpy/utils/streamlines.py

When using dummy metadata with `scil_streamlines_math.py` I get an error because it tries to modify a `tuple` object.
This should fix the issue.
I'll test more extensively soon and then I'll remove the WIP.

Bug fix for fake metadata in streamlines math

---

scilpy/utils/streamlines.py

Avoid moving the original sft when cutting invalid streamlines: save the
original space/origin, and move the streamlines back to the original
space/origin.

ENH: Avoid moving the original sft when cutting invalid streamlines

---

scilpy/utils/streamlines.py

Return streamlines in original space after applying a spatial
transformation: save the original space/origin, and move the streamlines
back to the original space/origin after transformation.

ENH: Return data in original space when transforming streamlines

---

scilpy/io/utils.py
scripts/scil_compute_connectivity.py
scripts/scil_compute_hdf5_average_density_map.py
scripts/scil_compute_mean_fixel_afd_from_hdf5.py
scripts/scil_remove_similar_streamlines.py

Remove unused default process count parameter from the process count
validation method.
Take advantage of the commit to:
- Document the method behavior if the process count is not contained in
the arguments.
- Fix the returned value docstring.
- Fix the logged process count in script.

ENH: Remove unused default process count parameter

---

scilpy/image/datasets.py
scilpy/io/utils.py
scilpy/tracking/local_tracking.py
scilpy/tracking/propagator.py
scilpy/tracking/seed.py
scilpy/tracking/tracker.py
scilpy/tracking/tracking_field.py
scilpy/tracking/utils.py
scripts/scil_compute_local_tracking.py
scripts/scil_compute_local_tracking_2.py
scripts/scil_compute_local_tracking_dev.py
scripts/tests/test_compute_local_tracking_dev.py

**Bigger changes:** 
- **Merging the tracker and the propagator** into propagator to avoid circular reference. Old file tracker.py (containing the two classes) becomes propagator.py
- Adding a main **script** scil_compute_local_tracking_2.py (other names suggested?)
- New "Tracker" class
- Englobes the track() function that was previously alone in local_tracking.py. This will allow creating a child version in dwi_ml.     File renamed tracker.py
- Now the main script is: 1) Initialize the tracker. 2)  Tracker.track(). 
- So to be clear, this new "Tracker" is absolutely not the same as the old, it is one step above. See new diagram:
https://docs.google.com/presentation/d/1mvvBYjKZ-IVmkl1EYWBTQ_8T8H0R3_Y-/edit?usp=sharing&ouid=101323301275554058305&rtpof=true&sd=true 
**Smaller changes:** 
- …

Modifications in the (bitbucket) tracking scripts - part 2

---

scripts/scil_evaluate_bundles_individual_measures.py

Following Laurent's problem with the script, this is a simple fix.
Laurent was manually uniformizing his bundle and doing QC on the results. He was then using scil_compute_bundle_voxel_label_map.py and also doing QC.
Then when he was using this script, it was automatically flipping head/tail (originally for simplicity) rendering all his QC useless.
Now, turning off the uniformization/flipping is possible.

Optional uniformize

---

scilpy/io/fetcher.py
scripts/tests/test_compute_asym_odf_metrics.py
scripts/tests/test_execute_asymmetric_filtering.py

Use new data for tests.
New data are a subsampled fODF volume and its asymmetric counterpart to speed up the tests for fODF denoising scripts.
@arnaudbore

Update test data for processing and tracking

---

scripts/scil_compute_connectivity.py

Switch the computation of the average metrics in a bundle, use the same as in scil_compute_mean_std.py for identical results.
The previous method gave weird results when outliers were present in the maps.

compute_connectivity fix average

---

scilpy/tracking/propagator.py

Here it is, the minor change that had to be done in order to support tracking on asymmetric ODF!
It requires nothing more than using a full SH basis in the `ODFPropagator` class when the data is found to be in full SH basis.

Asymmetric tracking unlocked for dev tracking scripts

---

scripts/scil_compute_sf_from_sh.py

Add option to scale SF by the given b0, to be symmetrical with `scil_compute_sh_from_signal.py` when using `--use_attenuation`
- Requires a b0 to be given as input
- Fixes a bug where bvecs corresponding to b0 images are not removed before building the sphere, causing additional bvecs to be created when normalizing the "b0-bvecs"

Add option to scale SF by the b0 in scil_compute_sf_from_sh.py

---

scilpy/reconst/multi_processes.py
scripts/scil_compute_msmt_fodf.py
scripts/tests/test_compute_msmt_fodf.py

Multi-tissue fODF estimation can throw `ArpackNoConvergence` error when the solution does not converge inside a voxel for some `cvxpy/numpy/scipy` version combinations. The problem occurs when using `cvxpy >= 1.1.15` but I didn't find where it comes from specifically.  It is one possible workaround, we could also just force the cvxpy version if you prefer.
I also used the opportunity to solve PEP8 style issues.
It is also unclear to me why it crashes when running it locally from the command line but not through pytest (also local).
@karanphil @arnaudbore

Bug fix: Multi-tissue fODF convergence error

---

scilpy/tracking/propagator.py
scilpy/tracking/tracker.py

For the `dev` tracking scripts.
We  don't use `get_opposite_direction` for backward tracking anymore so supplying a non-symmetric sphere should not be a problem, right? @EmmaRenauld  could you confirm this is ok?
I removed the `ValueError` which is raised in the `PropagatorOnSphere` constructor when a `repulsion` sphere is supplied. Also fixed some docstrings.

[BF] Remove exception for non-symmetric sphere for dev tracking

---

scilpy/io/utils.py

Fixing some doc:
1) `args: list` raises a warning in editors such as pycharm, as it is actually a Namespace.
2) missing parameters

Fixing doc in io.utils

---

scilpy/viz/scene_utils.py
scripts/scil_compute_msmt_fodf.py
scripts/scil_visualize_fodf.py

There was a minor bug with the `vf_rgb` when nan values occured in `shm_coeff`. In the script `scil_compute_msmt_fodf.py`, we changed any nan for 0 in `shm_coeff`, but forgot to do so in `vf`, so that when calculating `vf_rgb`, we were dividing by nan, resulting in a `vf_rgb` full of nan. This has been fixed by a simple 2 lines change.
Also, the parameter `bg_range` in `scil_visualize_fodf.py` was not working for rgb background. The value_range parameter was removed when calling `actor.slice` and instead, we now apply the value_range manually on the texture before sending it to `actor.slice`. This works for both scalar and rgb data.

Fix vf stuff

---

scripts/scil_validate_and_correct_bvecs.py

@mdesco
Better docstring to ease keyword search, for example :
```
scil_search_keywords.py gradients
scil_search_keywords.py flips
```

Better docstring for scil_validate_and_correct_bvecs

---

scripts/scil_resample_tractogram.py

Make it clearer on the default behavior.
New parameters make it easier to subsample a lot of tractogram using bash but without upsampling the small ones.

Improve DOC on scil_resample_tractogram.py

---

scilpy/image/datasets.py

The condition for `is_voxel_in_bound` is wrong in the `DataVolume` class.
Because we are in `voxmm` space with origin `corner`, the volume bounds should be `[0, dims[0][`, `[0, dims[1][`, `[0, dims[2][`.
Take for example a volume 1mm-iso with a length of 2 along some axis. The first voxel is contained between indices `[0, 1[` mm and the second voxel is contained between indices `[1, 2[` mm. The previous condition would have placed the upper bound at `1`, and therefore ignored the last slice completely.
Do you agree @EmmaRenauld ?

Fix wrong condition for is_voxel_in_bound used in dev tracking

---

scilpy/image/operations.py
scilpy/segment/streamlines.py
scripts/scil_compute_endpoints_map.py
scripts/scil_compute_qbx.py
scripts/scil_filter_tractogram.py
scripts/tests/test_compute_endpoints_map.py
scripts/tests/test_filter_tractogram.py

I worked a bit with tractogram filtering scripts this week, and here is a list of very small changes.
- My pycharm was sometimes confused by the datatypes. Clarifying docstrings.
- Adding --binary option to scil_compute_endpoints maps.
- Adding verbose option to scil_compute_qbx.
- Adding option to save rejected streamlines in scil_filter_tractogram

Small fixes and improvements in tractogram filtering scripts

---

scilpy/tracking/tools.py
scripts/scil_filter_streamlines_by_orientation.py
scripts/tests/test_filter_streamlines_by_orientation.py

New script to filter a tractogram based on total changes in x, y or z directions. There is a note explaining that x, y, z mean the x,y,z coordinates of the sft streamlines, not necessarily aligned with the real x,y,z coordinates of the brain.
This will be useful to separate cingulum streamlines from the CC in our new tractometer based on ROI, using scil_score_tractogram (upcoming).

Adding new filtering script by orientation

---

scilpy/tracking/tracker.py
scripts/tests/test_compute_local_tracking_dev.py

Small fix: coordinate type was a tuple when expected to be an array. Script was still running, but streamline contained one tuple and n-1 arrays. 
Also changing test from --nt 1000 to --nt 10. Decreasing this test time from 46 seconds to 2 seconds on my computer.

Fixing coordinate type + decreasing test size in dev tracking

---

scilpy/tracking/propagator.py
scripts/scil_compute_local_tracking_dev.py

Add a warning when using rk_order > 1 with probabilistic tracking in `_dev` tracking. Set default `rk` order to 1.
Might close #560, or should we keep the issue opened until we reimplement our rk integration correctly for prob tracking?
@EmmaRenauld @StongeEtienne

Warn user for rk > 1 with prob tracking in dev tracking

---

scilpy/io/fetcher.py

Removing unused imports and variables. Adding missing variable in the docstring. Adding a line to fix pep8.

Clean pep8 in the fetcher file

---

scilpy/io/utils.py
scilpy/tractanalysis/scoring.py
scripts/scil_score_tractogram.py
scripts/tests/test_score_tractogram.py

Mainly two changes (although that makes a lot of changed lines, sorry!)
- Including the options `--gt_heads, --gt_tails`, and the grount truth bundle directly into the json config file. This way:
-  Options can vary per bundle
(ex: use only the head/tail ROI for one, but include a ground truth mask for another)
-  Same ROIs can be used for many bundles
(ex: a ROI named 'occipital' could be used to define many bundle without having to copy it locally as bundle1_head and bundle2_head)
- A lot less dangerous to mix up the order of the bundles
(compared, say, to using `--gt_head *_heads --gt_tails *_tails`)
- Changed the code to deal with streamline ids instead of streamlines themselves (as per the #todo that was left).
Also, I now compute each bundle from the whole tractogram instead of from …

Modifying scil_score tractogram

---

scilpy/tracking/propagator.py
scilpy/tracking/seed.py
scilpy/tracking/tracker.py
scilpy/tracking/utils.py

- Encapsulated parts for easier management with dwi_ml.
(Multiprocessing does not need to save data to tmpdir and load it back because we use hdf5 files with lazy use, which deal well with multiprocessing).
- Made the processing frequency param (this way, I can have more prints in dwi_ml).
- Added docstring.
- Removed unused method in the propagator.
- Removed the comment #todo must be better designed for dipy: I don't thing we intend to change this.
- Sending line instead of line[-1] to propagator. In our case, propagator sometimes needs to know where you are coming from.

Small changes in the dev tracker

---

scripts/scil_split_image.py
scripts/tests/test_split_image.py

Here is a small script that splits an image at certain given indices along the last dimension (so all the directions). I needed this to split a nifti file that had something like this: b-values = 0, 1500, 1500, 1500, 1500, 0, 1500, 1500, 1500, 1500, splited into separate dwi1_b0.nii.gz, dwi2_b0.nii.gz, dwi1_b1500.nii.gz and dwi2_b1500.nii.gz. The command for this particular example would be:
`scil_split_image.py dwi.nii.gz dwi.bval dwi.bvec 1 5 6 --out_dwi dwi1_b0.nii.gz dwi1_b1500.nii.gz dwi2_b0.nii.gz dwi2_b1500.nii.gz --out_bval dwi1_b0.bval dwi1_b1500.bval dwi2_b0.bval dwi2_b1500.bval --out_bvec dwi1_b0.bvec dwi1_b1500.bvec dwi2_b0.bvec dwi2_b1500.bvec`
where the input is dwi.nii.gz, dwi.bval and dwi.bvec.
By default, if no output names are given, the script will take the input names …

Add split image script

---

scilpy/tracking/local_tracking.cl
scilpy/tracking/tracker.py
scripts/scil_compute_local_tracking_gpu.py

Addresses some (but not all) of the enhancements suggested in issue #583 .
In particular:
* Add compress streamlines option;
* Save streamlines on-the-fly using `LazyTractogram` (so much faster and way more memory-friendly);
* Add random number generator seed for reproducibility;
* Add `forward_only` mode for disabling backward pass.

Enhance GPU tracking

---

requirements.txt
scilpy/tractanalysis/features.py

A warning was fixed in dipy 1.4.1 in file bundles_distances_mdf (used in Recobundles), where a warning was printed erroneously in previous versions. It made me want to verify if we could upgrade dipy a little.
Changed requirements.
I created a clean environment, pip installed requirements successfully, pip installed scilpy successfully. 
Tests seem to pass.

Upgrading dipy

---

scripts/scil_concatenate_dwi.py

When concatenating more than 2 DWI volumes, the same indices are reused for each volume, resulting in the concatenation of the first and last supplied volumes with a lot of 0s in the remaining dimensions. This solves the issue.

[BF] Fix bug in scil_concatenate_dwi.py when supplying more than 2 images

---

scilpy/tractanalysis/scoring.py
scripts/scil_score_tractogram.py

As discussed with @AntoineTheb , f1 score computing must use first version of the overreach, not version divided by |A| as in http://tractometer.org/ismrm_2015_challenge/evaluation
Cleaning vocabulary.

Fix F1 score

---

scilpy/image/datasets.py
scilpy/io/image.py
scilpy/tracking/propagator.py
scilpy/tracking/seed.py
scilpy/tracking/tracker.py
scripts/scil_compute_local_tracking.py
scripts/scil_compute_local_tracking_dev.py
scripts/scil_compute_seed_density_map.py
scripts/tests/test_compute_local_tracking.py
scripts/tests/test_compute_local_tracking_dev.py

So far in our script, we coded everything in voxmm, and use the `voxmm_to_...` methods of the DatasetVolume. I needed the equivalent methods starting from vox space for dwi_ml.  So, base idea of this PR: to add methods in the DatasetVolume such as `vox_to_voxmm`, `is_vox_in_bound`, etc.
But, looking back at the code made me realise there were some incoherencies We called 'vox' space something that did not depend on the origin, which does not fit with dipy's usage. Clarified those methods names. 
Another change:  Other scripts such as scil_compute_seed_density_maps use seeds in vox space, center origin. Modified.
Note. Summary:  
- dipy uses voxmm, center. 
- scil_compute_local_tracking uses voxmm, corner
- scripts using seeds use vox, center.
- dwi_ml uses vox, corner (because torch's …

Clarify vox space

---

scilpy/tractanalysis/scoring.py
scripts/scil_score_tractogram.py
scripts/tests/test_score_tractogram.py

I was not able to differentiate to of my bundles with all the criteria already present. I added a 'must_pass_mask' (I am totally open to another name!).
So far we have
- endpoint mask or head + tail: where the streamlines must start and end
- gt_mask: the mask that will be used to compute the statistics (Overlap, Overreach)
- limits_mask: all streamlines must entirely stay inside that mask.
This adds:
- must_pass_mask: streamlines must pass through that region to be included in the bundle.
(Careful if you accept Antoine's PR before mine, I'll check if it needs refactoring)
@AntoineTheb

Added a 'must_pass_mask'

---

scilpy/viz/scene_utils.py
scripts/scil_visualize_fodf.py

Small modifications to `scil_visualize_fodf.py` and `scene_utils.py` in order to be able to set a uniform color for the ODFs as RGB and to set also a uniform color for the overall background of the image, which is usually black by default.
Maybe @CHrlS98 and @jhlegarreta can test it quickly.

Add arguments for RGB color ODF and RGB background color

---

scripts/scil_compute_local_tracking_dev.py

As discussed in #624, change default interpolation for tracking mask in dev tracking script.
Closes #624 .

Change default interpolation for mask

---

scilpy/tractanalysis/scoring.py

I came over a weird case, with a bundle found with 0% overlap, 100% overreach.
The f1 fails with a division by 0. In that case, by definition, the f1 score (Dice score) = how good you are, should be 0.

Fix rare division by 0 in f1

---

scilpy/gradientsampling/optimize_gradient_sampling.py
scripts/scil_generate_gradient_sampling.py

Very small change in the `scil_generate_gradient_sampling.py` script, in order to get a gradient table readable by a Philips scanner. Indeed, Philips scanners require that the gtab have unique pairs of bvecs and bvals for each line. By default, the script outputs the same pair of bvecs [0, 0, 0] and bvals [0] for each bvals in the gtab. The added option simply copies the bvecs from the previous line for each bvals, except the first one.
To test this, simply run the script, for example `scil_generate_gradient_sampling.py 16 32 64 dwi --eddy --duty --b0_every 18 --bvals 500 1000 2000 --mrtrix --b0_philips`, and make sure that no b0 has the same bvecs.

Gradient sampling ajustment

---

scilpy/tractanalysis/scoring.py

Oups, sorry....
I seem to have inverted the two versions of the Overreach scores in the final json (computation was ok). Fixed and clarified.

Fix: names for overreach

---

scripts/scil_recognize_multi_bundles.py

The previous fix on logging did not fix file handle (saving to file).
This was observed when RBx-Flow was crashing due to missing file.

Fix logging for RBx (file handling)

---

scilpy/tractanalysis/scoring.py

Again a mini-fix, sorry.
vb_count (ex; 25 valid bundles) was used rather than vs_count (number of streamlines).

Fix total count

---

scilpy/viz/scene_utils.py

`scil_screenshot_volume_mosaic_overlap.py` does not work anymore because of the `bg_color` arg added to `scene_utils.create_scene`. Make optional so that everything works again.
@jhlegarreta @karanphil

[BF] BG color as optional function argument

---

scilpy/image/labels.py
scilpy/io/image.py
scripts/scil_analyse_lesions_load.py
scripts/scil_combine_labels.py
scripts/scil_compute_bundle_mean_std_per_point.py
scripts/scil_compute_bundle_volume_per_label.py
scripts/scil_compute_connectivity.py
scripts/scil_compute_seed_by_labels.py
scripts/scil_decompose_connectivity.py
scripts/scil_dilate_labels.py
scripts/scil_filter_tractogram.py
scripts/scil_filter_tractogram_anatomically.py
scripts/scil_normalize_connectivity.py
scripts/scil_remove_labels.py
scripts/scil_split_volume_by_ids.py
scripts/scil_split_volume_by_labels.py
scripts/scil_visualize_scatterplot.py
scripts/tests/test_combine_labels.py
scripts/tests/test_split_volume_by_ids.py

One step into the cleaning of the modules. It seems an easy one to start with, not too much chances to get mixed up with something else.
I placed it in `scilpy.image.labels.py`.
I cleaned the 5 labels scripts that I found. Their main now only do imports and saving.
- scil_combine_labels
- scil_dilate_labels
- scil_remove_labels
- scil_split_volume_by_ids
- scil_split_volume_by_labels
I moved `scil.io.image.get_data_as_label` into scil.image.labels, explaining the other modifications. It could also be kept in io as it does fetch the data from the img.

Creating module 'labels'

---

.gitignore
requirements.txt
scilpy/io/fetcher.py
scripts/tests/test_execute_angle_aware_bilateral_filtering.py
setup.py

To decrease the length of scripts tests, mocking is used to skip code blocks or algorithm calls that take too long.
Here, the call to `scilpy.denoise.bilateral_filtering.angle_aware_bilateral_filtering` is mocked, so the actual filtering is never executed. The whole script executes up to the call to `angle_aware_bilateral_filtering`, where the created mock is activated and returns the expected filtered volume, upon which the end of the script executes. Thus, everything in the script around the specific function is still tested.
Here is the command to run the test : `pytest scripts/tests/test_execute_angle_aware_bilateral_filtering.py --script-launch-mode inprocess`
The argument `--script-launch-mode inprocess` is mandatory for mock to work with pytest-console-script, else a new process is …

[ENH] POC : Use mocking to get faster execution of tests

---

scripts/scil_remove_invalid_streamlines.py

Tractometry-Flow was crashing if centroids have 0 streamlines because `scil_remove_invalid_streamlines.py` was saving empty files at the end of RBX-Flow.
A new --no_empty option will avoid this problem.

--no_empty in scil_remove invalid streamlines.py

---

scilpy/image/labels.py
scilpy/image/tests/test_labels.py
scilpy/version.py
scripts/scil_split_volume_by_labels.py

np.unique() was sorting the results and changing the length which was messing up the naming convention.
I discovered it while trying Tractoflow ABS and it was not working at ALL (the mask where all messed up).
I simply removed the np.unique() and now it is the job of the user to have a decent LUT

Fix the unique len issue

---

scilpy/io/image.py
scilpy/utils/streamlines.py
scilpy/viz/chord_chart.py
scilpy/viz/scene_utils.py
scilpy/viz/utils.py
scripts/scil_assign_custom_color_to_tractogram.py
scripts/scil_compute_bundle_voxel_label_map.py
scripts/scil_estimate_bundles_diameter.py
scripts/scil_filter_tractogram.py
scripts/scil_screenshot_bundle.py
scripts/scil_uniformize_streamlines_endpoints.py
scripts/scil_visualize_connectivity.py

Modifying existing scripts to facilitate Laurent's life with coloring bundles when doing connectomics-like approach.
The Uniformize endpoints scripts now accept ROIs (similar to the --drawn_roi X.nii.gz 1:5) to perform a head/tail flip based on the proximity to the ROI's barycenter (rather than an x/y/z method).
Then a new coloring option was added to color along the length using default OR custom colormap (declared as `--colormap red-orange-yellow-green-blue-pink`)
To be tested by Laurent first.

Coloring connectomics

---

scilpy/connectivity/utils.py
scripts/scil_reorder_connectivity.py
scripts/tests/test_reorder_connectivity.py

Add a new automatic ordering method (to go from sparse matrix to dense along the diagonal). This works best on thresholded matrices.
The OLO has to be computed on a single matrix (--optimal_leaf_ordering) and then apply to all others (--in_ordering).
The previous behavior still works. --in_ordering is still a text file with two rows of integers to do the indexing in X and then Y (supports non-square output)
The behavior for the output filename convention changed a bit, before if you called the script with:
`scil_reorder_connectivity.py */*.npy --in_ordering config.txt --out_suffix _reo` 
it would create all the matrices with a suffix **in the current folder**, now they are saved with the suffix in **their original folder**. _To mimic the previous behavior:_
`scil_reorder_connectivity.py …

Added OLO to reorder_connectivity

---

scilpy/tracking/seed.py
scilpy/tracking/tracker.py

During multiprocessing Pool, the argument sent is a dict, but the multiprocessing sends it as *args, thus deconstructing the dict.
Modifying to (dict, ), so that instead it will diconstruct the tuple and leave the dict intact.
Not sure how we did not find this bug sooner... Sorry.

Fix multiprocess in dev tracking

---

README.md

I lost quite some time trying to figure out why I couldn't create a virtual environment for python3.10. Turns out I was missing the `python3.10-venv` package.

Add python3.10-venv to packages to install

---

scilpy/io/utils.py
scripts/scil_search_keywords.py

No matter the permission the `__init__.py` was giving that error when calling `scil_search_keywords.py `with the `--search_parser` option
`PermissionError: [Errno 13] Permission denied: '/home/rhef1902/Libraries/scilpy/scripts/__init__.py'`
The second change is actually a commit mistake, but it simply supports `.mat` files from ANTs for both single and double precision matrices.

skip __init__ in search_keyword.

---

scripts/scil_compute_seed_density_map.py
scripts/scil_compute_streamlines_density_map.py

Uses uint8 if args.binary ==  1
This is the default in scilpy and MI-Brain for binary mask (0/1)

uint8 in compute_density when possible

---

scripts/scil_compute_fodf_max_in_ventricles.py

Small PR to allow the use of the `scil_compute_fodf_max_in_ventricles.py` script with 2D data or small dimensions 3D data. Just make sure it doesn't break other stuff that uses it (it should since the code is exactly the same when small_dims=False).

Adding small_dims option to scil_compute_fodf_max_in_ventricles

---

scripts/scil_compute_fodf_max_in_ventricles.py

Simply adding some explanation to the `scil_compute_fodf_max_in_ventricles.py` script about the way the data is scanned.

Adding explanations to scil_compute_fodf_max_in_ventricles

---

scilpy/tracking/local_tracking.cl
scilpy/tracking/tracker.py

Weird errors reported by @frheault with GPU tracking.
I wonder if this helps!

[BF] GPU tracking kernel cannot be called main

---

requirements.txt
scripts/scil_get_version.py

Script to help us all debug collaborators when they are not familiar with Git.
This should be used when a collaborator was setup some time ago and we forgot how.
It will be useful in a while (when everyone is up-to-date), but I believe it will be useful.
Could also be a quick way to check 'version' when working across multiple devices/containers/clusters
It outputs:
```
You installed Scilpy with pip on 2023-04-02
The closest release is 1.5
Your Scilpy directory is: /home/frheault/Libraries/scilpy
Your current Origin is: git@github.com:frheault/scilpy.git
Your repository is on branch: get_version_script
The last commit hash is: 2414097218727a5ae4c28677cfe251fec2ec1b6e
The last commit date is: 2023-04-02, by frheault
The last commit message is: Clean pep8
Your upstream is set to: …
```

Get version script

---

scripts/scil_assign_custom_color_to_tractogram.py

Somehow `import matplotlib.pyplot as plt` was removed from the `scil_assign_custom_color_to_tractogram.py` script, so the `save_colorbar` function did not work. I guess that the colorbar option is rarely used so that went under the radar...
Fixed it!
@frheault

Adding import matplotlib to assign_custom_color_to_tractogram

---

scripts/scil_assign_custom_color_to_tractogram.py

Here is a small fix from Stan to add some options for manually choosing the colormap bounds in `scil_assign_custom_color_to_tractogram.py`. @frheault 
Added note : Stanislas also tested these changes on his setup and it works.

Adding options for normalization in scil_assign_custom_color_to_tractogram

---

scripts/scil_compute_fodf_metrics.py

Hi, I added a `absolute_peak_values` option to `scil_compute_fodf_metrics.py`, because right now, we return the `peak_values` normalized per voxel and the `peaks` are also multiplied by these `peak_values`, so we kind of have the information in double. Doing so, we lose any idea of peaks scale between the voxels, since the first peak of each voxel has a `peak_value` of 1.
What I propose is to save the actual peak amplitudes as `peak_values` and to save the `peaks` (peak_dirs) as unit vectors. This way, we keep a way to compare between voxels, and we can still easily apply the `peak_values` per voxel if we want afterwards.
In order to not break any existing pipeline, I put it as an option and kept the legacy way as default.
@CHrlS98  @mdesco @frheault @arnaudbore , I think this concerns …

Adding absolute_peak_values to scil_compute_fodf_metrics.py

---

requirements.txt
scilpy/image/operations.py
scilpy/utils/util.py
scripts/scil_compute_bundle_voxel_label_map.py
scripts/scil_harmonize_json.py

New operations for scil_image_math.py to do patch-wise correlation (3,3,3) between two images.
Useful between density maps (different algo, test-retest, etc)

Correlation ops

---

requirements.txt
scilpy/utils/util.py
scripts/scil_harmonize_json.py

Simplify handling of missing data in the JSON for tractometry analysis.

(WIP) Harmonize json

---

scripts/scil_tractogram_math.py

Allow tractogram math script to run as such: without the
```
if __name__ == "__main__":
main()
```
block, the script does simply not call `main` and does not perform any computation.

BUG: Allow tractogram math script to run as such

---

scilpy/io/utils.py
scilpy/viz/scene_utils.py
scilpy/viz/utils.py
scripts/scil_screenshot_volume.py
scripts/scil_screenshot_volume_mosaic_overlap.py
scripts/tests/test_screenshot_volume.py

Add capabilities to display mask overlays as contour instead of transparency. Integration into mosaic overlay script and new script to create multiple screenshots from one volume. Multiple examples are provided in the scripts documentation for tests.

Display masks as contours in screenshots

---

scilpy/tracking/tracker.py
scripts/scil_compute_local_tracking.py
scripts/scil_compute_local_tracking_dev.py

Just for a better user experience. Previously, option -v in scil_compute_local_tracking did not output any verbose at all. No way to know if the code has even started.
Using TQDM, with a refresh rate of 1% of the total number of seeds (only with option -v).
Also sneeking in a verification of the format with save_seed option.
Example of output:

ENH: Verbose tracking

---

scripts/scil_compute_ihMT_maps.py

Here is a small modification to the computation of ihMTsat. Previously, it was in fact the ihMTdR1sat that was calculated. To output this metric, use the `--legacy_sat` option. If not, the real ihMTsat will be computed.
@Manonedde

Correct ihMTsat

---

scilpy/tracking/tracker.py
scilpy/tracking/utils.py
scripts/scil_compute_local_tracking_dev.py

In the tracking dev, manage the stopping criteria as in Dipy:
- If direction is invalid (angle or ODF threshold): do not add the next point.
- (Previous usage was to add an additional straight point instead)
- Else, if out of tracking mask: the point is added, and *then* the streamline is stopped.
- (Was already like that, but out of the for loop).
Add this choice to doc so that it is more obvious for the user.

Make stopping criteria  more obvious + more similar to dipy.

---

scilpy/io/fetcher.py
scilpy/tractograms/tests/tests_tractogram_operations.py
scilpy/tractograms/tractogram_operations.py
scripts/scil_tractogram_math.py
scripts/tests/test_compute_pca.py
scripts/tests/test_tractogram_math.py

[WIP] Need to check if other tests are needed.
Some fixes from testing:
- In the script scil_tractogram_math: to use a robust operation, you're supposed to send operation 'difference' and option --robust. But if you send operation 'difference_robust', it was accepted. You could end up with operation 'difference_robust_robust'. Modifying accepted operations in argparser.
- If you want to do, example, intersection of many big files: it was concatenating all files (doubling eveything in memory) and then keeping only the few accepted streamlines. Inversing: First filtering the sft, (freeing memory), then concatenating. Encapsulated that step out of the main code to be able to test it.
- Robust intersection seemed buggy to me.  Lines `if not union_mode or not difference_mode` are always true, …

Unit test tractogram operations

---

.devcontainer/devcontainer.json
.devcontainer/setup_container.sh
.gitattributes
docs/source/documentation/devcontainer.rst
docs/source/index.rst

PR adding to the repository the necessary files to enable the creation of a development container in VS Code. Once merged, users will be able to automatically create a development environment through VS Code, that contains the whole Scilus development stack (ANTs, FSL, Mrtrix, etc.), and develop Scilpy in it.
In addition to VS Code, this requires Docker, to create the development container - spawning the containers takes a few minutes (depending on the user's internet speed). The containers comes pre-equiped with Git and several VS Code extensions to streamline development, and is connected to docker outside the container (so it can build images as well).
Once created, VS Code opens an IDE inside the container, where Scilpy is installed. The user can then develop Scilpy, interact with …

Working Scilpy development container for VS Code

---

.devcontainer/Dockerfile
.devcontainer/devcontainer.json
.gitattributes

This PR needs to be merged fast, it contains a hotfix for the new .gitattributes file.
The new .gitattributes that fixes line endings on clones and checkouts as too broad and caused checkout errors. This makes it more granular, so that correct files have correct line endings, based on their extension.
Steps to reproduce bug :
1) Create a new virtual environment
2) Run : pip install git+https://github.com/scilus/scilpy.git@1.4.0
Correct behavior (using my fork which does not have the .gitattributes file) :
1) Create a new virtual environment
2) Run : pip install git+https://github.com/AlexVCaron/scilpy.git@1.4.0
I updated devcontainers as well, an update to the feature system made it impossible to build a container directly on top of scilus:latest (no git, nor wget/curl was present).

Fix bug with new .gitattributes

---

scilpy/denoise/asym_averaging.py
scilpy/gradientsampling/optimize_gradient_sampling.py
scilpy/io/utils.py
scilpy/io/varian_fdf.py
scilpy/reconst/bingham.py
scilpy/reconst/divide_fit.py
scilpy/reconst/multi_processes.py
scilpy/reconst/raw_signal.py
scilpy/segment/models.py
scilpy/segment/recobundlesx.py
scilpy/tractanalysis/features.py
scilpy/tractanalysis/reproducibility_measures.py
scilpy/utils/metrics_tools.py
scripts/scil_apply_transform_to_tractogram.py
scripts/scil_combine_labels.py
scripts/scil_compute_bundle_mean_std_per_point.py
scripts/scil_compute_ssst_fodf.py
scripts/scil_remove_invalid_streamlines.py
scripts/scil_remove_labels.py
scripts/scil_shuffle_streamlines.py
scripts/scil_uniformize_streamlines_endpoints.py
scripts/tests/test_fix_dsi_studio_trk.py
scripts/tests/test_generate_gradient_sampling.py
scripts/tests/test_visualize_bundles_mosaic.py

Fixed my pycharm warnings.
- Fixed "function X does not have a parameter X"
- Fixed "unused imports"

Fix a few warnings

---

scilpy/viz/screenshot.py
scripts/scil_screenshot_bundle.py

Simple features for Laurent that allow you to add ROI (and colors) to the screenshot tools.
It is called like this: `scil_screenshot_bundle.py atlas/pop_average/AF_L.trk mni_masked.nii.gz  --roi a.nii 255 0 0 --roi b.nii 0 255 0 --roi c.nii 0 0 255  -f`
There is 3 mode, the simplest shows the ROI as white, but if you specify RGB or RGBA after you can pick the color
```
For the --roi argument: If 1 value is provided, the ROI will be white,
if 4 values are provided, the ROI will be colored with the RGB values
provided, if 5 values are provided, it is RGBA (values from 0-255).
```
If the user use the wrong number of value (1, 4 or 5 is accepted) you get `--roi must be used either with PATH or with PATH R G B  or PATH R G B A`

Custom ROI surface rendering for Laurent

---

scilpy/io/utils.py
scripts/scil_tractogram_math.py
scripts/scil_verify_space_attributes_compatibility.py

The current behavior of `scil_tractogram_math` (or rather, `is_header_compatible_multiple_files`) does not allow for tractogram operations on TCKs.  This fixes this behavior by comparing the TCK's reference or, in the case of two TCKs, bypassing the comparison as they will  use the same reference.
Fixed some pep8 warnings also. 
edit: Added `--reference` parameter to `scil_verify_space_attributes_compatibility.py` too. It can be considered not useful as the reference used for loading the validated tck could just be passed to the script, but I say why not.

ENH:  `scil_tractogram_math` support for TCKs

---

scilpy/reconst/aodf.py
scripts/scil_compute_asym_odf_metrics.py

- 2 functions out of the script
- new module aodf.py in reconst
Test passed.

Asym clean up

---

scilpy/io/utils.py
scilpy/tracking/tracker.py
scripts/scil_compute_local_tracking.py

The `symmetric724` sphere is suboptimal for probabilistic tractography because the vertices density is higher at the poles. 
- Change default sphere to `repulsion724`. This change affects all scripts with input spheres.
- Change the default sphere for GPU tracking.

RF - changed tracking default sphere from symmetric724 to repulsion724

---

scripts/scil_score_bundles.py

There was a bug in scil_score_bundles where the invalid bundles were incorrectly loaded if --compute_ic was used in scil_score_tractogram.
The bug caused the same tractogram to be loaded for each invalid bundle, which itself was not necessarily an invalid bundle, messing up the results.

FIX: bug in scil_score_bundles.py

---

scilpy/tracking/propagator.py
scilpy/tracking/seed.py
scilpy/tracking/tests/notes.txt
scilpy/tracking/tests/test_propagator.py
scilpy/tracking/tests/test_seed.py
scilpy/tracking/tests/test_tracker.py
scilpy/tracking/tools.py
scilpy/tracking/tracker.py
scripts/scil_compute_local_tracking_dev.py

- Adding an option to the _dev tracking to have fixed seeds. This allows to create a figure like this:
- Changing the --discard_last_point option to make it the default choice (as discussed with Gab and other; this makes it more like Dipy)
- Fixing the way the numpy generator and seed are used, as per the[ numpy doc](https://numpy.org/doc/stable/reference/random/generated/numpy.random.seed.html). If you think it's not the best way to do it, I can just delete the last commit.

ENH: Adding option to skip randomization of seed. + other fixes

---

MANIFEST.in
scilpy/io/deprecator.py
scilpy/version.py
setup.py

`importlib.metadata.version` doesn't work for package not installed with pip, i.e. when using a local editable version (https://github.com/python/importlib_metadata/issues/364)
The problem is solved by calling  `scilpy.version`  instead of  `metadata.version`. 
@arnaudbore @AlexVCaron do you see a problem with this change?

BF - metadata version when using editable install

---

scripts/scil_visualize_bundles_mosaic.py

Since our switch to Pillow==10.0.*, the script `scil_visualize_bundles_mosaic.py` was not working, apparently... the function `getsize()` from Pillow does not exist anymore, we should use `.getbbox()` or `.getlength()` instead. I adapted the script.
@AntoineTheb @frheault 
https://pillow.readthedocs.io/en/stable/releasenotes/9.2.0.html

Fixing scil_visualize_bundles_mosaic.py with Pillow 10.0.*

---

scripts/scil_uniformize_streamlines_endpoints.py

Very small PR!
The help from option --auto was copy-pasted in option --centroid.

[Fix] Change wrong help description

---

scripts/scil_gradients_modify_axes.py
scripts/tests/test_gradients_modify_axes.py

Tentatively fixing issue #816 
We did not find a way to use letters. The arpgarser does not understand text that starts with a minus.
Choices discussed to tell script to flip the x axis:
1. `x` is normal direction, `X` is flipped.
2. `x` is normal direction, `x-` is flipped
3. `x` is normal direction, `ix` is 'inversed' x.
4. Use numbers:  negative ints are understood. But uses axes = 1, 2, 3 because with 0, 1, 2, we can't inverse 0 with -0.
We chose 4 with @karanphil. @mdesco ok for you?

[FIX] Use numbers rather than letters in scil_gradients_modify_axes

---

scripts/legacy/tests/test_legacy_scripts.py

no error output is : `scripts/legacy/tests/test_legacy_scripts.py::test_help_option[inprocess] PASSED `

TST - remove legacy warnings

---

scripts/scil_fodf_msmt.py

Addressing issue #830 from @mdesco , I added a tolerance argument to `scil_fodf_msmt.py`. It was simply hardcoded to tol=20 in one function, and set to default (20) in another. This was in fact a potential breaking point even if it ran. I just had to give the option.
@mdesco could you try to run it again on your setup? Thanks!

Adding tolerance argument to fodf msmt

---

scilpy/io/fetcher.py

Tests are not passing because of a confirmation on large file download from gdrive. This fies the endpoint used so the confimation works.
...
Run the tests or wait for Jenkins

fix gdrive endpoint for tests

---

scilpy/tracking/utils.py
scripts/scil_tracking_local.py
scripts/tests/test_tracking_local.py

Mapping the SH to SF before tracking speed up det/prob by a factor 2X and PTT by 10X.
**requires dipy 1.8.0+**
...

OPT - map sh to sf before tracking [requires dipy 1.8.0]

---

Jenkinsfile
README.md

Publish coverage reports to codecov.io after testing
...
[Report on Codecov.io](https://app.codecov.io/github/scilus/scilpy/tree/feat%2Fcodecov)

add step to publish coverage to codecov.io

---

scripts/scil_frf_set_diffusivities.py
scripts/tests/test_frf_set_diffusivities.py

I added multi-shell support to `scil_frf_set_diffusivities.py`. It only took a few modifcations, and single-shell works as before. This was added with the goal of running it in nf-scil. I added tests also, and a check on the format of the input new_frf.
...
...

Adding msmt support to set_frf_diffusivities

---

scilpy/gradients/bvec_bval_tools.py
scilpy/gradients/tests/test_bvec_bval_tools.py
scilpy/image/volume_operations.py
scilpy/io/gradients.py
scripts/scil_NODDI_maps.py
scripts/scil_freewater_maps.py
scripts/scil_gradients_convert.py
scripts/scil_gradients_modify_axes.py
scripts/scil_tractogram_commit.py

Unit tests for methods in bvec_val_tools.
(Moved `fsl2mrtrix` and `mrtrix2fsl` out of there, to `io.gradients`, because they load and save data. To avoid having to load data in unit tests).
...
`pytest scilpy/gradients/tests/test_bvec_bval_tools.py`

Unit tests: gradients.bvec_bval_tools

---

.github/workflows/test.yml

Disable workflow run on forks. The workflow will still trigger, but all jobs will be skipped
...

disable test run on forks

---

.coveragerc
.github/workflows/test.yml

Codecov.io is not finding the changes associated to the uploaded coverage metrics. This PR will address this, but it is done through iterative fixing.
...
codecov.io will tell everything

Fix coverage sources

---

.coveragerc
.github/workflows/test.yml
pytest.ini

Paths between the source, the coverage report and codecov were muddled. I moved .coverage at the root, and now codecov can execute there and everything is golden.
...

Fix coverage report paths

---

scilpy/dwi/operations.py
scilpy/dwi/tests/test_operations.py
scilpy/dwi/tests/test_utils.py
scilpy/io/varian_fdf.py
scripts/scil_dwi_detect_volume_outliers.py

In preparation for next unit tests (in module dwi), finish cleaning the main of all scripts in the column DWI of our super excel file. Remaining files were:
- scil_dwi_detect_volume_outliers: Most of the main copy-pasted into a method. Absolutely no change made.
- scil_prepare_topup and scil_prepare_eddy: I give up for these two. No unit test for now.
- scil_dwi_convert_FDF: Was aldready clean, but in module io instead of module dwi. Arnaud choose to keep as is.
So in summary: Absolutely no line of code changed here.
...
...

Finish cleaning the main of dwi_ scripts, to allow eventual unit tests

---

.coveragerc
.github/workflows/test.yml

Codecov is not super stable right now. When the coverage upload fails, we need to re-run the whole test suite (long). This PR splits the workflow in twain, so only the second job fails when codecov push fails. Then, to retry the upload, re-run the workflow, specifying to run ONLY the failed jobs. Voilà ?

Ability to resume workflow when codecov push fails

---

scilpy/gradients/gen_gradient_sampling.py
scilpy/gradients/tests/test_gradients_utils.py
scilpy/gradients/utils.py
scripts/scil_dwi_reorder_philips.py

Unit tests for the file gradients_utils.
As discussed, not sure about the random sphere thing... Went back to [Caruyer's code](https://github.com/ecaruyer/qspace/blob/1da50557db5d8869189d564c72bbca8808f387c4/qspace/sampling/sphere.py#L98), and it says on the half-sphere! Anyone understand why?
...

Add gradient_utils unit tests

---

scilpy/viz/scene_utils.py
scripts/tests/test_screenshot_volume.py

`scil_screenshot_*` scripts were broken because of a fix in Pillow. See:
https://stackoverflow.com/questions/76616042/attributeerror-module-pil-image-has-no-attribute-antialias
Replaced `ANTIALIAS` with `LANCZOS`, now they work.
...

FIX: screenshot functions no longer working

---

scilpy/gradients/bvec_bval_tools.py
scilpy/gradients/tests/test_bvec_bval_tools.py
scilpy/io/btensor.py
scilpy/io/utils.py
scilpy/reconst/frf.py
scilpy/reconst/sh.py
scripts/scil_btensor_metrics.py
scripts/scil_dki_metrics.py
scripts/scil_dti_metrics.py
scripts/scil_dwi_detect_volume_outliers.py
scripts/scil_dwi_extract_b0.py
scripts/scil_dwi_to_sh.py
scripts/scil_fodf_memsmt.py
scripts/scil_fodf_msmt.py
scripts/scil_fodf_ssst.py
scripts/scil_frf_memsmt.py
scripts/scil_frf_msmt.py
scripts/scil_frf_ssst.py
scripts/scil_qball_metrics.py
scripts/scil_sh_to_sf.py
scripts/tests/test_dti_metrics.py
scripts/tests/test_dwi_detect_volume_outliers.py
scripts/tests/test_dwi_extract_b0.py
scripts/tests/test_dwi_to_sh.py
scripts/tests/test_fodf_ssst.py
scripts/tests/test_frf_msmt.py
scripts/tests/test_frf_ssst.py
scripts/tests/test_qball_metrics.py
scripts/tests/test_sh_to_sf.py

1. [ENH] The argument --force_b0_threshold, used a bit everywhere, was quite unclear. Does it force to use the b0_threshold given, or does it force to work in any case? Answer was: it forced to use the minimal b-value even if it was higher than expected b0_threshold. Renamed --skip_b0_validation.
2.  [FIX] In many cases, the function `check_b0_threshold` was incorrectly used in the scripts (they were using `check_b0_threshold(args)` but the function expected a bool as first argument. It was thus not doing as expected.
3. [FIX] In other cases, it was used with: `b0_thr = check_b0_threshold(force_b0_threshold, bvals.min(), bvals.min())` which was not doing anything!
4. [ENH] It was always used with the default b0_threshold. Added an argument b0_threshold that user may change if there is an …

Clarify b0 threshold

---

scripts/scil_frf_mean.py
scripts/tests/test_frf_mean.py

Quick PR to add support and test for multi-shell FRF in `scil_frf_mean.py`. Should be easy to review.
...
...

Adding msmt support and test to scil_frf_mean

---

scilpy/io/mti.py
scripts/scil_mti_maps_MT.py
scripts/scil_mti_maps_ihMT.py
scripts/tests/test_mti_maps_MT.py
scripts/tests/test_mti_maps_ihMT.py

Continuing the verification of reconst scripts.
Here, only touching the two mti_maps scripts. I did not succeed to encapsulate any parts of code that could be testable.
However, ~160 lines of codes in both scripts were exactly copy-pasted. I tried to at least put them together. Tell me if you don't agree.
Also, in the tests, the same filenames were copy-pasted many times. Simplifying by defining them once at the top. Easier to read.
...

Cleaning reconst scripts, part 3.

---

scilpy/io/mti.py
scripts/scil_mti_maps_MT.py
scripts/scil_mti_maps_ihMT.py

New little PR! First, I changed the name of the function `io.mti.verifications_and_loading_mti` to `io.mti.load_and_verify_mti`. Then, I simply added two new local functions `_parse_acquisition_parameters` and `_prepare_B1_map`, making the big function less big.
...
...

Split load_and_verify_mti function

---

requirements.txt

Update DVC now that iterative/dvc-data#513 is merged
test_aodf_metrics.py will pass and that says it all

Update dvc requirements

---

scilpy/io/utils.py
scilpy/reconst/mti.py
scilpy/reconst/sh.py
scripts/scil_NODDI_maps.py
scripts/scil_NODDI_priors.py
scripts/scil_mti_adjust_B1_header.py
scripts/scil_qball_metrics.py
scripts/scil_sh_convert.py
scripts/scil_sh_fusion.py
scripts/scil_sh_to_rish.py
scripts/scil_sh_to_sf.py
scripts/tests/test_NODDI_maps.py
scripts/tests/test_sh_to_sf.py

Checked the final scripts in our reconst column. Didn't find anything to take out of mains: no new function. Only more comments, fixing prints, etc.
...
...

Reconst scripts part4

---

scilpy/tracking/utils.py
scripts/scil_tracking_local.py
scripts/scil_tracking_local_dev.py

Remove the toDo, related to Issue #698 
Also noticed that an option was added in utils (`--sh_to_pmf`) but it is only used in the main tracking script, not in the _dev. Moved option.
Also added a comment about the missing ptt_options usage. See Issue #952.

Close issue 698

---

scilpy/io/hdf5.py
scilpy/io/streamlines.py
scilpy/tractograms/streamline_and_mask_operations.py
scilpy/tractograms/tests/test_streamline_and_mask_operations.py
scilpy/viz/utils.py
scripts/scil_bundle_mean_fixel_afd_from_hdf5.py
scripts/scil_connectivity_compute_matrices.py
scripts/scil_connectivity_hdf5_average_density_map.py
scripts/scil_tractogram_apply_transform.py
scripts/scil_tractogram_apply_transform_to_hdf5.py
scripts/scil_tractogram_assign_uniform_color.py
scripts/scil_tractogram_commit.py
scripts/scil_tractogram_convert_hdf5_to_trk.py
scripts/scil_tractogram_cut_streamlines.py
scripts/tests/test_tractogram_apply_transform.py
scripts/tests/test_tractogram_apply_transform_to_hdf5.py
scripts/tests/test_tractogram_assign_uniform_color.py
scripts/tests/test_tractogram_cut_streamlines.py

Verified the four first tractogram scripts.
1. `scil_tractogram_apply_transform`: 
- Fixed difference between the doc's explanation and the script's management of option --remove_invalid.
2. `scil_tractogram_apply_transform_to_hdf5`:
- Made the same choices of management of invalid as in script 1.
- ENCAPSULATED HDF5 MANAGEMENT IN SCILPY.IO.HDF5.  (Many of these methods are not used here but will be in the next PR. I just wanted to make sure right now that everything fitted correctly).
3. `scil_tractogram_assign_uniform_color`:
- Moved loading of the json file out of the loop.
- Better explanation in parser
- Better verifications in main
- Encapsulated hexadecimal_to_RGB in viz.utils.
4. `scil_tractogram_cut_streamlines`:
- Now the data_per_streamline is kept. …

Tractogram scripts part1

---

scilpy/io/hdf5.py
scilpy/io/utils.py
scripts/scil_bundle_mean_fixel_afd_from_hdf5.py
scripts/scil_connectivity_compute_matrices.py
scripts/scil_connectivity_hdf5_average_density_map.py
scripts/scil_tractogram_apply_transform_to_hdf5.py
scripts/scil_tractogram_commit.py
scripts/scil_tractogram_compress.py
scripts/scil_tractogram_compute_TODI.py
scripts/scil_tractogram_compute_density_map.py
scripts/scil_tractogram_convert.py
scripts/scil_tractogram_convert_hdf5_to_trk.py
scripts/scil_tractogram_segment_bundles_for_connectivity.py
scripts/tests/test_tractogram_commit.py
scripts/tests/test_tractogram_compute_TODI.py
scripts/tests/test_tractogram_convert_hdf5_to_trk.py

- Using the hdf5 methods from part 1 in scripts where I found hdf5 usage.
- scil_tractogram_commit: clarifying. Adding test coverage.
- scil_tractogram_compress: ok!
- scil_tractogram_compute_density_map: ok!
- scil_tractogram_compute_TODI: clarifying. After discussion with @frheault , moving option --normalize out of the if.
- scil_tractogram_convert: ok!
- scil_tractogram_convert_hdf5_to_trk: Clarifying help. More checks. --labels_list and --save_empty were both needed OR both not used. Merged the two args.

Tractogram scripts parts2

---

scilpy/io/streamlines.py
scilpy/io/utils.py
scilpy/tracking/utils.py
scilpy/tractanalysis/bundle_operations.py
scilpy/tractograms/streamline_operations.py
scilpy/tractograms/tractogram_operations.py
scripts/scil_tracking_local.py
scripts/scil_tracking_local_dev.py
scripts/scil_tracking_pft.py
scripts/scil_tractogram_apply_transform.py
scripts/scil_tractogram_cut_streamlines.py
scripts/scil_tractogram_detect_loops.py
scripts/scil_tractogram_dpp_math.py
scripts/scil_tractogram_extract_ushape.py
scripts/scil_tractogram_filter_by_anatomy.py
scripts/scil_tractogram_filter_by_length.py
scripts/scil_tractogram_filter_by_orientation.py
scripts/scil_tractogram_filter_by_roi.py
scripts/scil_tractogram_remove_invalid.py
scripts/scil_tractogram_segment_bundles_for_connectivity.py
scripts/scil_tractogram_smooth.py
scripts/tests/test_tractogram_detect_loops.py
scripts/tests/test_tractogram_dpp_math.py
scripts/tests/test_tractogram_project_streamlines_to_map.py
scripts/tests/test_tractogram_smooth.py

Next step of scripts verification.
- `scil_tractogram_detect_loops`: 
- Clarified the argparser: arguments --qb and --threshold were either both required or both not used, so they were basically the same argument. Merged. 
- Added a --no_empty option.
- `scil_tractogram_dpp_math`:
-   argument --out_name was not really the output tractogram name, but the output dpp/dps name. Confusing. Changed to --out_key_name.
- Moved some checks higher to do them before loading stuff.
- Added more tests for better code coverage.
- `scil_tractogram_extract_ushape`: 
- Using `ranged_type`; verifications not needed anymore.
- Moving stuff a bit.
- There was a return (old line 88) that could potentially prevent the rest of happening (print counts, save remaining_tractogram). Fixed.
- …

Tractogram scripts parts3

---

scilpy/segment/tractogram_from_roi.py

The scoring script (`scil_tractogram_segment_and_score.py`) crashes if it only has NCs due to a restriction of np.concatenate (can't concatenate nothing). 
To test:
Data: https://drive.google.com/file/d/1Y0faJeSrvujcwaOUUbMsKwo9-DWyWrtw/view?usp=sharing
Requires the FiberCup's scoring data to be in your working folder. Then:
`scil_tractogram_segment_and_score.py tractogram_Angular30FiberCup__2024-04-17-05_50_50_fibercup.trk scil_scoring_config.json crash -f -v --dilate 2 --compute_ic --unique`

FIX: scorer crash if only NC and --unique

---

scilpy/tracking/utils.py
scripts/scil_tracking_local.py
scripts/tests/test_tracking_local.py

PR #750 forgot to include the PTT options for the `script scil_tracking_local.py` (issue #952). This PR fixed the issue.
`scil_tracking_local.py disco/fODF.nii.gz disco/DiSCo1_ROIs.nii.gz disco/mask.nii.gz scil_test2.tck --step 0.2 --theta 20 --npv 1 --algo ptt --sphere repulsion724 -f --probe_quality 5 --probe_length 2`

NF - add PTT options to the local tracking script

---

scilpy/reconst/fodf.py
scilpy/reconst/frf.py
scilpy/reconst/tests/test_fodf.py
scilpy/reconst/tests/test_frf.py
scripts/scil_fodf_max_in_ventricles.py
scripts/tests/test_frf_set_diffusivities.py
scripts/tests/test_frf_ssst.py

Took a few minutes today to prepare some unit test in the reconst module. 
Coverage of unit test changes (only; no script tests) are:
`reconst.fodf`: from 0% to 36%
`reconst.frf`: from 0% to 49%
Unchanged reconst files:
`reconst.aodf` = 0% (@CHrlS98 if you want to contribute)!
`reconst.bingham` = 88% (Thanks Charles)
`reconst.divide, reconst.mti, reconst.sh` = 0% (@karanphil if you want to contribute!?)
`reconst.utils`: 36%

Easy tests reconst

---

scilpy/image/tests/test_volume_math.py
scilpy/image/tests/test_volume_operations.py
scilpy/image/volume_math.py
scilpy/image/volume_operations.py
scilpy/io/utils.py
scilpy/tractanalysis/reproducibility_measures.py
scilpy/tractanalysis/tests/test_reproducibility_measures.py
scripts/scil_bundle_label_map.py
scripts/scil_dwi_compute_snr.py
scripts/scil_header_print_info.py
scripts/scil_tractogram_fix_trk.py
scripts/scil_tractogram_pairwise_comparison.py
scripts/scil_volume_math.py
scripts/tests/test_volume_crop.py

New tests for more code coverage, ye!!
Changes: 
- volume_math: 
- Tests: added a test for the correlation method, was missing. Fixes issue #940 .
- Methods: Moved sub-method (`def correlate`) out of the loop.
- volume operations:
-  Tests: Added 3 tests
-  Methods:
-  `register_image`: My initials tests failed because my fake images were too small. Took me a long time to figure out. Added a verification. 
- `compute_snr`: verified if both noise_mask and noise_map were given. Added more explanation.
- script scil_header_print_info: I wanted a faster way to print the affine. Added an option. You can tell me if there was an other way.
...

Volumes test

---

scripts/scil_surface_convert.py

Big start to scilpy mesh refactoring.  Fixed a typo in convert surface script.  Before fix script would only work with FreeSurfer surfaces.
...
- [ x ] Bug fix (non-breaking change which fixes an issue)
...
- [x ] My code follows the style guidelines of this project (run [autopep8](https://pypi.org/project/autopep8/))
- [x ] I added relevant citations to scripts, modules and functions docstrings and descriptions
- [ x] I have performed a self-review of my code
- [ x] I have commented my code, particularly in hard-to-understand areas
- [ x] I have made corresponding changes to the documentation
- [ x] My changes generate no new warnings
- [ x] I moved all functions from the script file (except the argparser and main) to scilpy modules
- [ x] I have added tests …

[FIX] fixed typo in surface convert script

---

scilpy/tractograms/tractogram_operations.py
scripts/scil_tractogram_math.py
scripts/scil_tractogram_pairwise_comparison.py
scripts/scil_tractogram_project_map_to_streamlines.py
scripts/scil_tractogram_project_streamlines_to_map.py
scripts/scil_tractogram_qbx.py
scripts/scil_tractogram_register.py
scripts/tests/test_tractogram_pairwise_comparison.py
scripts/tests/test_tractogram_project_map_to_streamlines.py
scripts/tests/test_tractogram_project_streamlines_to_map.py

Next step in tractogram scripts verification. All the next scripts were already pretty much ok! Yeah! Pretty much only formatting changes, and more verifications!
Stopped after 6 scripts. A part 6 will follow :)
- `scil_tractogram_math`
- `scil_tractogram_pairwise_comparison`
- `scil_tractogram_project_maps_to_streamlines`
- `scil_tractogram_project_streamlines_to_map`
- `scil_tractogram_qbx`
- `scil_tractogram_register`

Tractogram scripts part 5

---

scilpy/viz/color.py

There was only 8 colors in the BASE10 colors for visualization (with a white and a grey). Fixed, now there is 10, and they are all colors, no grayscale.
...
...

[FIX] 10 colors in BASE10 colors for visualization

---

scilpy/segment/tests/test_tractogram_from_roi.py
scilpy/segment/tractogram_from_roi.py

When using the _extract_vb_and_wpc_all_bundles function from the file `tractogram_from_roi.py`, there's a loop that updates and uses the **remaining_ids** list. While iterating over the bundles, it is possible that the list of remaining indices becomes empty thus creating an empty StatefulTractogram. This was causing some issues with the sub-function `filter_grid_roi_both` which internally was trying to transpose an empty matrix, which is invalid.
I added a quick check and some simple tests to make sure the sft provided as an input is not empty before filtering the streamlines w.r.t. the ROI.
```pytest scilpy/segment/tests/test_tractogram_from_roi.py```

[FIX] Empty remaining indices when filtering for a bundle

---

scilpy/surfaces/tests/test_surfaces_utils.py
scilpy/surfaces/utils.py
scripts/scil_surface_convert.py
scripts/tests/test_surface_convert.py
scripts/tests/test_tractogram_assign_uniform_color.py

Instead of using mri_info to get the xform, we can now use a reference file to convert the freesurfer surface to VTK for MI-Brain.
...
...

Removing xform from convert script

---

scripts/scil_dti_metrics.py
scripts/tests/test_dti_metrics.py

`scil_dti_metrics.py` is unusable due to a typo in the script. I assume in the tests and most usages, we ask to output FA, and it must be why we didn't detect this error, since `or` shortcuts evaluating `args.RGB`.
...
...

[FIX] Typo in scil_dti_metrics script

---

requirements.txt
scripts/scil_tractogram_convert.py

Allows user to save the good old VTK/FIB format in MI-Brain, similar logic to Stanislas PR for legacy surfaces, now for tractograms.
...
...

Update to work with Trimeshpy 0.0.4

---

scripts/scil_viz_fodf.py

When running `scil_viz_fodf.py path/to/fodf.nii.gz --background path/to/bg/image.nii.gz`, I get an issue saying that 'nearest' isn't a matplotlib colormap. This is caused because the interpolation argument is given as a positional argument whilst there's a missing argument to specify the colormap.
I explicitly put the default value there (None), but I'm also opened to change it to some other value. I could also change the function call to use keyword arguments instead of positional arguments (e.g. `interpolation=args.bg_interpolation`). 
...
- [ x ] Bug fix (non-breaking change which fixes an issue)

[FIX] Missing parameter for background viz

---

scilpy/tractanalysis/fixel_density.py
scilpy/tractanalysis/tests/test_fixel_density.py
scripts/scil_bundle_fixel_analysis.py
scripts/tests/test_bundle_fixel_analysis.py

Here is a script that computes a `fixel_density_maps` by associating each segment of streamlines in each voxel to one of the fixels. In other words, you give peaks and a list of bundles (.trk) as input, and it computes the fraction of each bundle per peak, for every voxel. It uses either the streamline count or some streamline weight in data_per_streamline, to compute the density of bundles. From the `fixel_density_maps`, we also get the `fixel_density_masks` (masked version of the map using thresholds), the `voxel_density_maps`, the `voxel_density_masks`, the `nb_bundles_per_fixel` and the `nb_bundles_per_voxel`. Please read the documentation of the script for more info.
@mdesco, @frheault  this is the script we talked about! I would recommend using the default values to start with. So …

[ENH] Bundle fixel analysis script

---

scripts/scil_bundle_fixel_analysis.py

I found a fossil in `scil_bundle_fixel_analysis.py`. The argument `bundles_mask` in the parser was not useful anymore. This should be quite simple to review and merge.
...
...

Removing unused argument in scil_bundle_fixel_analysis.py

---

scilpy/image/labels.py
scripts/scil_labels_from_mask.py
scripts/scil_lesions_info.py
scripts/tests/test_labels_from_mask.py

lesions_info now use labels as input because @AntoineTheb created the script scil_labels_from_mask.py. This avoids duplicated processing in the script, this also will be required in the future because I will add a few lesions-related scripts.
...
...

Modify lesions_info to support labels instead of mask

---

scripts/scil_lesions_info.py

I've put the min_lesion_volume option back in because the script doesn't work without it and the problem is that if I remove the option, the compute_lesion_stats script in scilpy.utils.metrics_tools takes a default value of 7mm without being able to change it. so we'll just have to make sure for now that when we use this script after scil_label_from_mask.py we keep the same minimum volume between the two scripts.
- Bug fix

return option min_vol_lesion

---

scripts/scil_tractogram_cut_streamlines.py

Change the minimum length of streamlines output by `scil_tractogram_cut_streamlines` to 0, as the previous behavior was confusing.
...
- X ] My changes generate no new warnings

ENH: cut streamlines min length

---

scripts/scil_bundle_shape_measures.py
scripts/scil_json_convert_entries_to_xlsx.py

Some scripts have been merged into scil_bundle_shape_measure.py because of that scil_json_convert_entries_to_xlsx was not able to do its job properly.
Best way to test this is to run tractometry_flow using this [PR](https://github.com/scilus/tractometry_flow/pull/31) with local scilpy installation.

[ENH][BF] Update json conversion to excel used in tractometry_flow

---

scilpy/tractanalysis/fixel_density.py
scripts/scil_bundle_fixel_analysis.py
scripts/tests/test_bundle_fixel_analysis.py

This is a small PR to add the option of not normalizing the density maps. For instance, if you want to keep the information about the streamline count or the sift2 weight, you can now use `--norm none`. You can also use multiple choices like `--norm voxel none` and it will produce outputs for both.
The for loop on the norm options makes it look like all the code has changed in the script, but it is basically the same as before inside the loop, with shorter variable names to respect pep8.
Enhancement
...

Add no norm option to scil_bundle_fixel_analysis

---

scripts/scil_volume_pairwise_comparison.py

A bug in a function call inverted the behavior of the `--ignore_zeros_in_BA` and `--ratio` parameters in `scil_volume_pairwise_comparison.py`

FIX: `ratio` arg in volume pairwise comparison

---

scilpy/io/utils.py
scripts/scil_frf_mean.py
scripts/scil_frf_memsmt.py
scripts/scil_frf_msmt.py
scripts/scil_frf_set_diffusivities.py
scripts/scil_frf_ssst.py
scripts/tests/test_frf_mean.py
scripts/tests/test_frf_memsmt.py
scripts/tests/test_frf_msmt.py
scripts/tests/test_frf_set_diffusivities.py
scripts/tests/test_frf_ssst.py

Add parameter to specify *floating point precision* of `fiber response functions` at saving, using the `fmt` parameter of `np.savetxt`.
...
...

[ENH] Add precision to FRF scripts

---

scripts/scil_volume_apply_transform.py
scripts/tests/test_volume_apply_transform.py

Add interpolation option to "scil_volume_apply_transform". Useful when transforming label maps where linear interpolation produces undesirable effects.
TODO

ENH: add interpolation to `scil_volume_apply_transform`

---

scripts/scil_tractogram_dpp_math.py
scripts/scil_tractogram_dps_math.py

Extention of this PR in response to François' comment
Documentation
Pep8 good, doesn't change tests.

Clarify doc to differentiate dpp_math with dps mode and dps_math

---

scilpy/tractograms/streamline_operations.py
scilpy/tractograms/tests/test_streamline_operations.py

As explained here: https://github.com/scilus/scilpy/issues/1073
`pytest scilpy/tractograms/tests/test_streamline_operations.py -k 'test_filter_streamlines_by_length'`

[FIX]: Return rejected streamlines with empty sft

---

scripts/scil_tractogram_filter_by_length.py
scripts/tests/test_tractogram_filter_by_length.py

Closes https://github.com/scilus/scilpy/issues/1007.
As the script's argument was unused in the code, it's unlikely to be break someone's code as specifying this argument wasn't doing anything. I renamed it to specify the output file path for the rejected streamlines instead of just specifying the flag so that the script user can control where the saved TRK goes.
...
`pytest scripts/tests/test_tractogram_filter_by_length.py -k 'test_rejected_filtering`

FIX: Filter streamlines by length, use the "save rejection" argument.

---

scilpy/io/hdf5.py

The `reconstruct_sft_from_hdf5` was considering dps as dpp when trying to load an hdf5 with dps (e.g., after commit of afd_fixel computation). There was simply a `.shape` missing in the assertion.
Closes #960 
...
Tested it locally, works fine now.

Fix the hdf5 error when dpp are present

---

scilpy/io/fetcher.py
scilpy/viz/backends/fury.py
scripts/tests/test_viz_volume_screenshot.py

Fix incomming deprecation fromFury. Also fixes some resource management problems by the test data fetcher. Closes scilus/scilpy#1059
...
pytest scripts/tests/test_viz_volume_screenshot.py

Fix Fury upcoming deprecation call

---

scripts/scil_gradients_generate_sampling.py

There was a small bug with the argument `--no_b0_start`, it was missing `action='store_true` and was just doing nothing.
...
...

Fixing bug in gradients_generate_sampling

---

scripts/scil_viz_gradients_screenshot.py

The reading of .bvals and .bvecs files was outdated in `scil_viz_gradients_screenshot.py`. I used read_bvals_bvecs instead. Also, I changed the last argument given to `assert_gradients_filenames_valid`, which was not working at all. (supposed to be a bool but was 'fsl' or 'mrtrix')
...
...

Update script scil_viz_gradients_screenshot

---

scilpy/connectivity/matrix_tools.py
scripts/tests/test_connectivity_reorder_rois.py

Condense distance matrix that was not. Pep8 + test pass

---

requirements.txt
scilpy/image/volume_b0_synthesis.py

update to dipy 1.10

---

scilpy/gradients/bvec_bval_tools.py
scilpy/io/btensor.py
scilpy/io/utils.py
scripts/scil_NODDI_maps.py
scripts/scil_dki_metrics.py
scripts/scil_fodf_msmt.py
scripts/scil_frf_msmt.py

See issue #1108 for more details. In summary, I realized that the `skip_b0_check` option forces the `b0_threshold` to become the minimal b-value, which doesn't work in some cases. Many scripts used the `check_b0_threshold` function without saving the outputted threshold, because we did not want to overwrite the `b0_threshold`. However, the warning message from `check_b0_threshold` with  `skip_b0_check` still said that the `b0_threshold` was changed to the minimal b-value, which was false in this case. 
A simple fix was to add a `overwrite_with_min` option to `check_b0_threshold`, so that if it is False, the warning says that the script will continue without b0s, as it does. I added this `overwrite_with_min=False` option to all scripts that had `will_overwrite_with_min=False` when calling …

Fixing the skip_b0_check function

---

scripts/scil_NODDI_maps.py

Script was not able to catch the error when mask and dwi don't have the same header
...
...

[BF] NODDI map catch error

---

scilpy/io/utils.py
scripts/scil_dwi_prepare_eddy_command.py
scripts/scil_dwi_prepare_topup_command.py

New versions of topup and eddy allow news options.
This PR makes them available for every versions if used with -f
...
...

[ENH] Allow extra option for topup and eddy

---

scilpy/io/utils.py

I added support for a list of lists of paths in `scil_assert_inputs_exist.py`. This arises when you mix `nargs='+'` with `action='append'`.
Closes #1067 
...
...

Adding support for list of lists of paths in assert_inputs_exist

---

scripts/scil_connectivity_filter.py
scripts/scil_connectivity_graph_measures.py
scripts/scil_connectivity_math.py

- Graph_measures: ok
- connectivity_math:  There was no check that the ref_matrix exists. Using the load_matrix method to do this check.
- connectivity_filter: 
- Added ref to Jasmeen's thesis
- Fix number in logging (said the number <, should have been <=)
- Simplify the code

Final connectivity scripts PR

---

scripts/scil_volume_stats_in_ROI.py
scripts/scil_volume_stats_in_labels.py
scripts/tests/test_volume_stats_in_ROI.py
scripts/tests/test_volume_stats_in_labels.py

Add new input features to 
- scil_volume_stats_in_labels.py
-  `in_map` was replaced by the argument group `Metrics input options`, allowing for a list of metric filenames or a metric folder;
-  if the scripts as multiple input metrics, the output json file has a new top level dict `metric`;
-  add `add_json_args` and corresponding formatting to the output json;
- this PR changes the interface of the script, i.e. it will break other scripts using it.
- scil_volume_stats_in_ROI.py
- change the positional argument `in_mask` to `in_rois`, allowing for multiple input mask.
- if the scripts as multiple input ROIs, the output json file has a new top level dict `roi_name`;
...
...

RF - Input to volume stats scripts

---

docs/source/fake_files/uncompress.py
scilpy/tractanalysis/connectivity_segmentation.py
scilpy/tractanalysis/fibertube_scoring.py
scilpy/tractograms/streamline_and_mask_operations.py
scilpy/tractograms/tests/test_streamline_and_mask_operations.py
scilpy/tractograms/uncompress.pyx
scripts/scil_tractogram_segment_connections_from_labels.py

For clarity, the `uncompress(.)` function was renamed `streamlines_to_voxel_coordinates`.
The module remains named `scilpy.tractogram.uncompress`.
...
...

DOC - renamed the uncompress fct to streamlines_to_voxel_coordinates

---

scripts/scil_mti_maps_MT.py
scripts/scil_mti_maps_ihMT.py

Here is a small PR adjusting two scripts for the new `assert_inputs_exist` function. I did not find other scripts where the new feature could simplify the code. Closes #1116 
...
...

Adjusting scripts for new assert_inputs_exist function

---

pytest.ini
scripts/legacy/tests/test_legacy_scripts.py

Legagcy flies currently ignored from pytest (generated too many warnings, Arnaud got tired).
Adding back to supervise any error.
Legacy scripts will be deleted in a few versions, but meanwhile, checking that they work.

Do not ignore legacy

---

.devcontainer/Dockerfile
.devcontainer/setup_container.sh

The devcontainer stopped to build correctly. I added a non-root user to the Dockerfile and slightly modified the installation of scilpy to target this user instead of root.
...
Open scilpy in VS Code and Reopen in Container

[FIX] Add non-root user to devcontainer

---

scripts/scil_tractogram_assign_uniform_color.py
scripts/tests/test_tractogram_assign_uniform_color.py

If you use scil_tractogram_assign_uniform_color.py and the tractogram you assigned color to is not in the dict the script was crashing. Now if you add -f it will find an extra color to use and save the new dict at the same place as the old one.
...
...

[BF] Add new color if dict_color is not enough

---

scilpy/io/fetcher.py
scilpy/utils/spatial.py
scripts/scil_volume_crop.py
scripts/tests/test_volume_crop.py

Pickles are path bound and unsafe. A json file is way easier to use and doesn't pose code injection problems.
...
pytest scripts/tests/test_colume_crop.py

Change Crop Volume BBOX for a json

---

scripts/scil_labels_combine.py

Fix output label indices parameter name in script doc example: use ``out_labels_ids`` instead of ``out_labels_indices`` to match the argument name,
Do not apply.
Not necessary

DOC: Fix output label indices parameter name in script doc example

---

scilpy/tractograms/streamline_operations.py
scilpy/tractograms/tests/test_streamline_operations.py
scripts/scil_tractogram_remove_invalid.py

The cut_invalid_streamlines  function has some corner cases not working when a streamline had its first point invalid.
This new version with new tests fixes it.
You can play with this data: [data.tar.gz](https://github.com/user-attachments/files/19782028/data.tar.gz)
...
...

[MAJOR][BF] Cut invalid streamlines

---

scripts/scil_gradients_validate_sampling.py
scripts/tests/test_gradients_validate_sampling.py

The script was not working with the .b filetype (mrtrix). I fixed the bug and added a test to catch it.
...
...

Small bug fix for scil_gradients_validate_sampling.py

---

scilpy/io/utils.py
scilpy/viz/backends/fury.py
scilpy/viz/backends/pil.py
scilpy/viz/color.py
scilpy/viz/screenshot.py
scripts/scil_viz_fodf.py
scripts/scil_viz_volume_screenshot.py
scripts/tests/test_viz_fodf.py
scripts/tests/test_viz_volume_screenshot.py

**Fixes:**
- scilpy.viz.backends.fury: Some wrong docstrings.
- scilpy.viz.backends.pil: Some wrong docstrings. Deleting function not used anywhere. Adding options in test for more coverage. Added some `\n` in the utils's help.
WIP BUG:
My test that I added to test_viz_fodf.py fails:
```
Traceback (most recent call last):
File "scripts/scil_viz_fodf.py", line 376, in main
image = compose_image(next(snapshots),
File "scilpy/viz/screenshot.py", line 189, in compose_image
draw_2d_array_at_position(canvas, img_scene, img_size,
File "scilpy/viz/backends/pil.py", line 302, in draw_2d_array_at_position
overlays_colors = generate_n_colors(len(overlays))
File "scilpy/viz/color.py", line 75, in generate_n_colors
_colors = np.concatenate(
ValueError: all the input arrays must have same number of …
```

Small fixes viz

---

scilpy/tractograms/streamline_operations.py

This function optimizes and simplifies `scilpy/tractograms/streamline_operations.cut_invalid_streamlines`. This PR alleviates some load from #1105 .
[test_pr_1105](https://github.com/user-attachments/files/18608970/test_pr_1105.zip)

ENH: optimize `cut_invalid_streamlines`

---

scripts/scil_bundle_label_map.py

`scil_bundle_label_map` could crash due to a wrong variable being checked. I fixed some PEP8 errors while at it.
[sub-c02_ses-01__CG_R_Po_.zip](https://github.com/user-attachments/files/20104880/sub-c02_ses-01__CG_R_Po_.zip)
`scil_bundle_label_map.py sub-c02_ses-01__CG_R_Po_ic.trk sub-c02_ses-01__CG_R_Po_centroid_20.trk tmp_dir -f`

FIX: scil_bundle_label_map crash

---

scilpy/image/tests/test_volume_math.py
scilpy/image/volume_math.py

This is the old behavior where you could do some volume operations (add, sub, div, mult) with numbers. 
...
...

[ENH][BF] Can use float or integer with some volume operation

---

scilpy/tractograms/streamline_and_mask_operations.py
scilpy/tractograms/streamline_operations.py

Actually reverts back to the functions removed in https://github.com/scilus/scilpy/commit/a7d2a5fb39c54002ef3e08ec3ff5da48fb9f5503, but in Python instead of Cython.
Future grad students may want to optimize them, but right now they're gonna do as is.
[sub-p19_ses-01__CC_Pr_Po.zip](https://github.com/user-attachments/files/20194005/sub-p19_ses-01__CC_Pr_Po.zip)
```bash
scil_bundle_label_map.py sub-p19_ses-01__CC_Pr_Po_cleaned.trk sub-p19_ses-01__CC_Pr_Po.trk tmp_out -f -v
```

FIX: Streamline cutting 3 - Tokyo drift

---

scripts/scil_bundle_label_map.py

Remove a streamline length threshold for the labelized streamlines. There was an edge case where the labels do not span the length of the streamlines, which caused no labelized streamlines to be saved. 
This is potentially an issue that stems from `compute_tract_counts_map`, as the labels **should** span the entire length of the streamlines.
In blue, the bundle
In green, the centroid
In red, the volume occupied by the computed labels.
[sub-33609_ses-V3__CC_Fr_2_.zip](https://github.com/user-attachments/files/20229080/sub-33609_ses-V3__CC_Fr_2_.zip)
```bash 
python scripts/scil_bundle_label_map.py sub-33609_ses-V3__CC_Fr_2_ic.trk sub-33609_ses-V3__CC_Fr_2_centroid_5.trk test_CC_Fr_2 -f -v DEBUG
```

FIX: scil_bundle_label_map min labelled streamline length

---

scilpy/tractanalysis/reproducibility_measures.py
scripts/scil_volume_pairwise_comparison.py
scripts/tests/test_volume_pairwise_comparison.py

Added Hausdorff distance to scil_volume_pairwise_comparison (https://en.wikipedia.org/wiki/Hausdorff_distance, "it is the greatest of all the distances from a point in one set to the closest point in the other set.") and the option to compare labels (ie multiple ROI per image) to a binary mask. 
Example use cases: comparing label maps to a tumor mask. Comparing JHU template regions to a MS lesion.  
Additionally, I removed a deprecation warning from numpy.
[test-1176.zip](https://github.com/user-attachments/files/20412670/test-1176.zip)
`scil_volume_pairwise_comparison.py labels_map.nii.gz test_1176.json --single_compare sub-PAT06__t1_warped_label-tumor_mask.nii.gz -f --labels_to_mask`

ENH: scil_volume_pairwise_comparison - hausdorff + labels-to-mask compare

---

scilpy/io/hdf5.py

An error was happening all the time when applying transform to HDF5 if DPP was discovered (even when told not to handle it). Added docs, remove error and added logging.warning instead.
...
...

Switch from error to warning for DPP in HDF5

---

scilpy/viz/backends/fury.py
scilpy/viz/slice.py
scripts/scil_viz_fodf.py

Here is some data to test: [single_voxel_dwi_MTR_SH.nii.gz](https://github.com/user-attachments/files/20715179/single_voxel_dwi_MTR_SH.nii.gz)
Closes #1181 
...
...

[BF] Fix odf viz with radial_scale_off option

---

scripts/scil_fodf_bundleparc.py

See title. --help was too long, due to bundles names being printed twice.
scil_fodf_bundleparc.py --help

ENH: shorten scil_fodf_bundleparc.py --help

---

.github/workflows/test.yml

Quick addition to the test workflows to install `vtk-osmesa` with scilpy. It is not built anymore in **containers-scilus** since (1) vtk distributes its own wheels, (2) mesa deb packages are officially distributed and  (3) selection of **offscreen-rendering** will be runtime from vtk 9.4 and onward.
**Why not upgrade to vtk 9.4 ?** I don't have time to do it, the patch will do enough for now. Once upgraded, we only need to remove the code.
...
Tests will run with the new **scilus/actions-runner:2.326.0-vtk9.2.6** (not deployed yet).

[HOTFIX] Install vtk-osmesa in workflow, not provided by runner anymore

---

scilpy/tractanalysis/reproducibility_measures.py

Script to compare binary mask and labels was not handling well all-zeros mask/label and was giving a warning. Now it simply write NaN to json without warnings.
...
...

Handle empty labels

---

scilpy/reconst/bingham.py
scilpy/tractanalysis/bingham_metric_along_streamlines.py
scilpy/tractograms/dps_and_dpp_management.py
scilpy/viz/backends/fury.py
scilpy/viz/backends/pil.py
scilpy/viz/color.py
scilpy/viz/gradients.py
scilpy/viz/screenshot.py
scilpy/viz/slice.py
scripts/scil_bundle_diameter.py
scripts/scil_fodf_to_bingham.py
scripts/scil_gradients_validate_sampling.py
scripts/scil_tractogram_assign_custom_color.py
scripts/scil_viz_bingham_fit.py
scripts/scil_viz_fodf.py
scripts/scil_viz_gradients_screenshot.py
scripts/scil_viz_tractogram_seeds_3d.py
scripts/scil_viz_volume_screenshot.py
scripts/tests/test_bundle_diameter.py
scripts/tests/test_tractogram_assign_custom_color.py
scripts/tests/test_viz_bingham_fit.py
scripts/tests/test_viz_fodf.py
scripts/tests/test_viz_gradients_screenshot.py
scripts/tests/test_viz_tractogram_seeds_3d.py
scripts/tests/test_viz_volume_screenshot.py
scripts/tests/test_viz_volume_screenshot_mosaic.py

**Adding some comments to ignore coverage, or adding tests to improve coverage**     
Below are listed the poorly covered functions in viz:
- scilpy.viz.backends.fury **(COVERAGE: FROM 73% TO  96%)**
- `create_interactive_window`: only used with option `--show_rendering` (or not `--silent`) in a few scripts. Cannot and will not ever be used in github. -----> Added a decorator to ignore.
-  Others already good or improved through other modifications below
- scilpy.viz.backends.pil **(COVERAGE: FROM  69% TO 76% )**
-  All already good or improved through other modifications below
- scilpy.viz.backends.vtk:  **(COVERAGE: FROM  12% TO  82% )**
- `lut_from_colors`, `create_tube_with_radii` and `contours_from_data`: improved through new options in tests.
- Others already good
- scil.viz.color : …

Ignore some cov viz

---

scilpy/connectivity/connectivity.py
scilpy/connectivity/matrix_tools.py
scilpy/connectivity/tests/test_connectivity.py
scilpy/connectivity/tests/test_matrix_tools.py
scilpy/tractograms/streamline_and_mask_operations.py
scripts/scil_bundle_diameter.py
scripts/scil_bundle_label_map.py
scripts/scil_tractogram_assign_custom_color.py

Adding unit tests for connectivity methods
- Deleted method `apply_olo`. Not used anywhere inside scilpy.
- Fixed `compute_triu_connectivity_from_labels`:
- Was putting the streamline count at the row / column of the matrix for the label's id, not the index of that label in the matrix.
- Was not using correctly map_coordinates.
Led to correcting map_coordinates a bit everywhere. **Explanation:**
Without `mode='nearest'`  (meaning, pad to nearest value when out of range), the default is to pad to 0 when outside the volume. The issue is that the first half of the voxels at the limit is considered out of range, as per following picture (thanks @AntoineTheb ):

Unit tests connectivity + FIX MAP_COORDINATES USAGE

---

src/scilpy/cli/scil_tractogram_math.py

I would expect, if I supply the argument `--save_empty` to the `scil_tractogram_math.py` script, that I get an output file containing an empty tractogram even if all the input tractograms are empty.
NB: Not having that output file created breaks extractor_flow (the one I'm actively implementing, but also the original implementation of extractor_flow).

[FIX] Still save empty file for scil_tractogram_math.py

---

src/scilpy/cli/scil_gradients_normalize_bvecs.py
src/scilpy/cli/tests/test_gradients_normalize_bvecs.py

The `scil_gradients_normalize_bvecs` script is normalizing **rows**, but it should be doing **columns** if we follow FSL gradients convention.
(Just a question, are there really people here with gradient files in **row ordering** ?)
1. Run the following to generate a **column ordered** bvec file easy to investigate :
echo -e "1 2 3\n1 2 3\n 1 2 3" > test.bvec
2. Using the **old version** of the  script, run : `scil_gradients_normalize_bvecs test.bvec out.bvec`. All rows will have the same values, columns won't be unit norm.
3. Using the **new version** of the script, run : `scil_gradients_normalize_bvecs test.bvec out.bvec`. Values should differ and columns have unit norms.

[FIX] Erroneous normalization of bvecs on rows

---

src/scilpy/cli/scil_volume_resample.py

When resampling using reference it didn't check the right part of the affine.
...
...

[BF] Fix check when resampling with a ref

---

src/scilpy/cli/scil_fodf_max_in_ventricles.py
src/scilpy/cli/tests/test_fodf_max_in_ventricles.py
src/scilpy/reconst/fodf.py
src/scilpy/reconst/tests/test_fodf.py

I added two options to `scil_fodf_max_in_ventricles`. First, we can now input a mask (ventricles or CSF) to help if the MD and FA thresholds don't work properly. Second, we can now use the median instand of the mean to compute the "max fodf". Indeed, I discovered that we take the mean of the maximum fODF in every voxels of the ventricles. I thought we were just taking the maximum value across all ventricle voxels, like the docstring suggested. The median can also help when we have outliers in the ventricles mask.
It would be nice if some people (@mdesco , @arnaudbore ) could test this with "normal data", be sure it does not change the result of the script.

Adding mask and median options to fodf max in ventricles script
